### ISSUE TITLE
Question (not really an issue) about DATA_LIMIT

### ISSUE THREAD

**Issue by sboubaker** [darold/ora2pg#1036]
Hello,
First I want to thank you for this wonderful tool which makes my life better 👍 
I have a small question but I didn't know where I should put it, so I choose GitHub/Issues space but feel free to remove because as I said I don't think that this is an issue:
MY question is: When executing Ora2pg with or without the "-L" flag. it seems that ora2pg divide the value I set by 1000. I mean when executing :

 ora2pg -t COPY -c dataload-ora2pg.conf  -j 2 -J 4  -L 800000

I got this on the log file:

[2020-11-24 09:16:49] DEBUG: number of rows 800 extracted from table MyTable
[2020-11-24 09:16:49] DEBUG: Formatting bulk of 800 data (real: 800 rows) for PostgreSQL.
[2020-11-24 09:16:49] DEBUG: Creating output for 800 tuples

Did I miss something?

Thanks again for your wonderful tool.

Sabri

**Comment by darold** [comment]
Hi,

This is because you  have BLOB in this table. In this case Ora2PG will divide by 10 the value of DATA_LIMIT until it reach a value under 1000. You can also set by yourself this limit for table with BLOB by setting BLOB_LIMIT. However when Ora2Pg found a table without BLOB it fall back to the DATA_LIMIT value.

**Comment by sboubaker** [comment]
Hi and Thanks a lot!

I really appreciate your reactivity.

Thanks again!

Sabri
