### ISSUE TITLE
Is the WHEN clause supported on TRIGGER migration?

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1055]
Hello.

I'm using ora2pg to migrate an Oracle DB to PostgreSQL and I noticed that when a trigger has a WHEN clause it is not correctly migrated to PG, although the WHEN clause is supported in PG.
Can you clarify it the tool does not supports this migration or am I doing something wrong, please?

Thank you!

**Comment by darold** [comment]
Hi,

Yes, since PG 9.0 Ora2Pg supports WHEN clause in trigger. Be sure that you are using latest Ora2Pg development code and verify that you are not using an old ora2pg.conf with PG_SUPPORTS_WHEN disabled. If PG_VERSION is set to a version upper than or equal to 9.0 the WHEN clause in trigger is automatically supported.

If you still have the problem, please port the Oracle trigger DDL.
