### ISSUE TITLE
Migrating data from a table that has a foreign key referring to itself fails

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1087]
Hello, First I want to say I'm very grateful for this really great open source tool.

I am currently testing moving data after having generated the schema, I am facing a problem with a table that has a foreign key referring to itself, it fails with the usual error: insert or update on table <table_name> violates foreign key constraint <fk_name>.

The only way I could make it work is to drop that foreign key and create it again after the migration, is this the only way? Will I need to generate the schemas with the constraints in a different file, then create those constraints after the data migration to avoid such problems?

**Comment by darold** [comment]
Hi,

You should have a look to DROP_FKEY in ora2pg.conf. Enabling it will drop the FK before data import and recreate them at the end for you.

If you prefer to not create constraint before importing data, Ora2Pg already save constraints and index DDL in separate files so that you can create the tables, import the data and applies the index+constraints.

**Comment by marie-joechahine** [comment]
Okay amazing, just tried it and works fine. However for one of the tables I was migrating some data violated a foreign key that refers to another table, the data was successfully moved but it failed on creating again the foreign key. I expected the data to be rolled back but the data was moved and the foreign key was dropped. I guess there is a configuration I also need to set so that in this case the migration is rolled back so that I don't have the data without the foreign keys, would that be LOG_ON_ERROR? Apologies if this should be obvious I am just starting with the tool.

**Comment by darold** [comment]
It depends how you are migrating the data. If you use direct import to PostgreSQL there is one transaction by chunk (DATA_LIMIT) of data exported. If you export all to files everything is enclosed in a single transaction in the main output file. However usually import is done in a parallel way so there is multiple transaction. LOG_ON_ERROR is not done for that but to be able to continue in case of error and process the failing data later. Here the problem is that you have a FK error, the only way is to fix the problem before importing the data.

**Comment by darold** [comment]
To be exact this is "there is one transaction by chunk (DATA_LIMIT) of data exported when LOG_ON_ERROR is enabled and one transaction per parallel process." The drop/create constraint are done in a separate transaction because of the multi-process mode.

**Comment by marie-joechahine** [comment]
I am importing directing for now, thank you for the explanation. Concerning the parallel processes it does not seem to work on Windows, if I set JOBS to 2 for example I get the message that I should use UNIX, is there a safe way around this?

**Comment by darold** [comment]
Yes it is not supported and will probably not.

**Comment by marie-joechahine** [comment]
Okay thank you, I have closed the issue as the DROP_FKEY configuration resolves it.
Great work.
