### ISSUE TITLE
Unexpected data when exporting data from a Date field oracle column to Date field column in PostgreSQL

### ISSUE THREAD

**Issue by marie-joechahine** [darold/ora2pg#1098]
I have a table with a column of type "Date" in Oracle in which the data is saved with the format "09-JUL-18".

When I export the data with the default being converted to timestamp, I get "2018-07-09 22:20:08", which i worry might get me problems since it is a different format.

So I added to the DATA_TYPE directive Date:Date so that ora2pg converts Date to Date instead of to timestamp in order to get the same value i have in oracle instead of the date with the time, I am now getting the exported data as "2018-07-09".

Since the Date type in PostgreSQL accepts the format "DD-MMM-YY" as an input according to the [documentation](https://www.postgresql.org/docs/13/datatype-datetime.html#DATATYPE-DATETIME-INPUT), why is it exporting to the "YYYY-MM-DD" format instead? Might there be a way to configure this?

**Comment by darold** [comment]
Ora2Pg translate date into timestamp by default because as you see actually Oracle stores it as a timestamp. Changing the DATA_TYPE translation is the right thing to do if this column was not use as a timestamp in Oracle.

About the date format actually it is not converted, this is just that we ask Oracle to return the timestamp in the ISO format using  NLS_DATE_FORMAT setting. Changing the output format to something else has no interest as it will be in the ISO format in PG or whatever date style you have set.

**Comment by marie-joechahine** [comment]
Okay understood, thanks for the clarification!
