### ISSUE TITLE
Oracle table PSSELECTCL converted PG table psPERFORMcl

### ISSUE THREAD

**Issue by fbamiere** [darold/ora2pg#110]
Hello Gilles, i think maybe,  i have found a small bug :

the Oracle table PSSELECTCL  : because it contains the word "SELECT" is converted to 

ps PERFORMcl table in the script for creating the indexes.

The two statements are failing because the table is named psselecttl in the pg database :
CREATE INDEX psseclefid ON psPERFORMcl (pssecodsel,pssecodeta,pssecodsit);
CREATE INDEX pssegrprej ON psPERFORMcl (pssegrprej);
 
Frédéric Bamiere (i was in training with you several month ago on ora2pg).
cheers.

**Comment by darold** [comment]
It might just have been fixed with last commit. Thanks Frederic for the report, you may found other wrong replacement of SELECT by PERFORM, this is the limitation of the regex. Ora2Pg is not able to distinct queries beginning with SELECT from other where the SELECT is part of a sub query. But this issue can be easily resolved.

Best regard,

**Comment by darold** [comment]
Solved

**Comment by fbamiere** [comment]
merci beaucoup.
Cordialement
 Frédéric Bamière
      De : Darold <notifications@github.com>
 À : darold/ora2pg <ora2pg@noreply.github.com> 
Cc : fbamiere <fbamiere@yahoo.com> 
 Envoyé le : Mercredi 18 mars 2015 11h25
 Objet : Re: [ora2pg] Oracle table PSSELECTCL converted PG table psPERFORMcl (#110)
   
Solved—
