### ISSUE TITLE
View Code objects are in uppercase

### ISSUE THREAD

**Issue by atlterry** [darold/ora2pg#1126]
Gilles; making progress on the import to pgsql...

Regarding view conversions - the view names are exported to lowercase ...
`CREATE OR REPLACE VIEW ssp_call_vw (cady_id, player_id, `

but the code in the view case is still in uppercase like so...

```
CADY.CADY_ID,
CASE WHEN PLAYER.PLAYER_ID=-1 THEN ''  ELSE CADY.CADY_ID END  PLAYER_ID,
get_do_list(PLAYER.cady_id) REFDO_LIST,
```

Is there a parameter to convert this or does this have to done manually?

Thanks

**Comment by darold** [comment]
There is not parameter for that but there is nothing to do because you not enable PRESERVE_CASE and PostgreSQL is case insensitive so cady_id is the same as CADY_ID provided that they are not double quoted.

If you want to beautify/format  the SQL code use https://github.com/darold/pgFormatter one day there will be an option to call pgFormatter from Ora2Pg but this is still not the case :-)

**Comment by atlterry** [comment]
I don't want the tables to be quoted in upper case so PRESERVE_CASE is disabled.  I did not know there was a pgFormatter - I'll take a look at it. Thanks
