### ISSUE TITLE
Manual updates - Trial & Error

### ISSUE THREAD

**Issue by atlterry** [darold/ora2pg#1138]
Hello Gilles; I was able to get a relatively clean export AFTER making some changes to the generated code; please correct me if I'm wrong with moving forward as I have several more schemas to migrate and this would be a good time to get my process documented.

**Differences: ora2pg   >   manual changes**
```
**View:** select fn(params...) colName   > fn(params...) colName
**Function Params**: 
timestamp 	> timestamp(0)
text		> varchar(n)
**Code Block**:
clock_timestamp()	> current_timestamp
to_number(to_char(in_date,'YYYY'),9999)	> to_number(to_char(in_date,'YYYY'), '9999')
last_day(in_date)-7	> last_day(in_date) - interval '7 days'

```
There are many config directives and I'm sure I have missed out a few  to make this process less manual and would appreciate a fresh set of eyes. Thanks

**Comment by darold** [comment]
Please add an example of the Oracle code so that I can reproduce and fix if necessary.

About clock_timestamp vs current_timestamp be aware that current_timestamp doesn't change in a transaction which is not the case for clock_timestamp():
```
gilles=# BEGIN;
BEGIN
gilles=*# SELECT clock_timestamp(), current_timestamp;
       clock_timestamp        |       current_timestamp       
------------------------------+-------------------------------
 2021-04-19 16:26:05.18971+02 | 2021-04-19 16:26:03.339085+02
(1 row)

gilles=*# SELECT clock_timestamp(), current_timestamp;
        clock_timestamp        |       current_timestamp       
-------------------------------+-------------------------------
 2021-04-19 16:26:12.638408+02 | 2021-04-19 16:26:03.339085+02
(1 row)
```
I think that Oracle behavior is like clock_timestamp().

For text vs varchar(n), why do you want to limit a column that do not have limits? Or perhaps you want to set the max length to Oracle VARCHAR2 limit, 32Kb? Ora2Pg use the text data type to translate a VARCHAR2 without length constraint and CLOB.

For timestamp  vs timestamp(0), this is the same a the DATE oracle datatype, actually the value saved is a timestamps with microseconds so Ora2Pg use the right type to not lost precision but if you don't care about it changing into timestamp(0) is the good choice.

If you want to generalize your custom translation for data type see directive `DATA_TYPE`.

For the other translation I need the Oracle code to understood what's wrong.

**Comment by atlterry** [comment]
Do you have an alternate email I can send the full code?

**Comment by darold** [comment]
Yes, my private email is gilles AT darold DOT net

**Comment by atlterry** [comment]
Gilles; I sent you the files via email; any feedback please?

**Comment by darold** [comment]
I have lost your email and don't remember if have fixed something else on this issue, however last commit  02acd92 fix potential problem in last_day conversion when USE_ORAFCE is off and a number is added or subtracted to the last day.

About `to_number(to_char(in_date,'YYYY'),9999)` the format specified a numeric and not string is not supported by Oracle, it should be written `to_number(to_char(in_date,'YYYY'),'9999')`
