### ISSUE TITLE
Cannot export emoji data

### ISSUE THREAD

**Issue by japinli** [darold/ora2pg#1285]
When I use ora2pg export data that has some emoji, it cannot work as expected.

For, example:

```sql
CREATE TABLE test_emoji(info clob);
INSERT INTO test_emoji VALUES ('emoji🌰');
```

Here is my ora2pg config:

```
[oracle@pgtool01 orauser]$ cat config/ora2pg_mk.conf
PG_VERSION      13
ORACLE_DSN      dbi:Oracle:host=127.0.0.1;port=1551;service_name=testdb
ORACLE_USER     orauser
ORACLE_PWD      xxxxxxxxxx
USER_GRANTS     1

NLS_LANG AMERICAN_AMERICA.UTF8
NLS_NCHAR UTF8
CLIENT_ENCODING UTF8

FUNCTION_CHECK 1
EXPORT_SCHEMA   1
COMPILE_SCHEMA  0
EXPORT_INVALID 1
TRANSACTION     READONLY
ENABLE_BLOB_EXPORT 1

SCHEMA          orauser
```

Then run:
```shell
$ ora2pg -t copy -o test.sql -c ora2pg.conf -a test_emoji
$ cat test.sql
...
COPY test_emoj (info) FROM STDIN;
emoji▒▒
\.
COMMIT;
...
```

I try to debug, and find it is `emoji\x{d83c}\x{df30}` in memory. Any thoughts?

**Comment by darold** [comment]
Are you sure that your data is stored correctly in Oracle? I do not have the problem, here is what I've to try reproduce your issue:
```
$ export NLS_LANG='AMERICAN_AMERICA.AL32UTF8'
$ export NLS_NCHAR='AL32UTF8'
$ sqlplus hr/oracle@orcl

[...]

SQL> @emoji.sql

Table dropped.


Table created.


1 row created.


Commit complete.

SQL> SELECT * FROM TEST_EMOJI;

INFO
--------------------------------------------------------------------------------
emoji🌰

SQL> 
```
Content of file:
```
$ cat emoji.sql 
DROP TABLE test_emoji;
CREATE TABLE test_emoji(info clob);
INSERT INTO test_emoji VALUES ('emoji🌰');
COMMIT;
```

Then after ora2pg export:
```
$ cat data/EMOJI_data.sql 
SET client_encoding TO 'UTF8';
SET synchronous_commit TO off;

TRUNCATE TABLE test_emoji;

COPY test_emoji (info) FROM STDIN;
emoji🌰
\.
```

I think the problem is that you have not set NLS_LANG and NLS_NCHAR before using `sqlplus` so the encoding to store the data is not the one you are expecting. Before running `sqlplus` use the following:
```
$ export NLS_LANG='AMERICAN_AMERICA.AL32UTF8'
$ export NLS_NCHAR='AL32UTF8'
```
For ora2pg you don't need to set these variables, just use Ora2Pg default which is set to the same encoding. but if they are set this should not be a problem.

**Comment by japinli** [comment]
@darold Thanks! Yeah, when removing `NLS_LANG` and `NLS_NCHAR` parameters in the config, it works. I try to set those parameters since an Oracle expert told me we should set those.
