### ISSUE TITLE
Assessment report and segregation of unsuccessfull conversions

### ISSUE THREAD

**Issue by Yasir1811** [darold/ora2pg#1293]
Hi Darold,
Is there any way we can get in the assessment report below details:
1) Number ,name and type  of objects that can be 100% converted into postgres by the tool
2) Number, name and type of objects that require manual efforts
3) Success rate of the schema conversion

Right now, I only see that the assessement report only shows type of objects and count and descrption.

I am using below statement for assessment report generation:

$ ora2pg -t show_report  --estimate_cost -c config/ora2pg.conf --dump_as_html > /tmp/orapgtestmigr/ora2pgreport.html

Another query is, when we run export_schema.sh , it puts all the converted objects in there respective folders. This also contains those objects that ora2pg fails to convert 100%.(it lists out warning over the top of statement).
 Is it possible, such doubtfull conversions be put into separate folders so that when we run import_all, we can only run those objects that are 100% converted by the tool and hence avoid errors during import?

Thanks!
Yasir

**Comment by darold** [comment]
Hi Yasir, in my experiences a migration is a whole, most of the time you can not just import fully converted objects because there is dependencies between them. Saying that you can also consider that everything can be imported directly outside functions, procedures and packages. But this is not something definitive, sometime there is issues with custom data type, constraints and sometimes functions and procedures can be imported without problem. But obviously most of the work is on stored procedure, knowing which object is 100% converted is useless what you want to know in an assessment is the approximate time it will take to migrate and the difficulties you will encounter. Ora2Pg gives all the necessary details about these difficulties but I agree that knowing how to interpret the report require some knowledge in Oracle to PostgreSQL migration.
