### ISSUE TITLE
question: how do we export e.g. 2 or 3 schemas from Oracle but not more?

### ISSUE THREAD

**Issue by mperdikeas** [darold/ora2pg#1294]
Hi, there's two things that are not clear to me from the documentation:
* how do we export from Oracle a number N (N > 1) schemas but no more?
* at which point should the decision be made? when invoking the migration template with `ora2pg --init_project ` or in the `ora2pg.conf` file when invoking `export_schema` or later still, when invoking `ora2pg -t COPY` ?

**Comment by darold** [comment]
Export them one by one creating a project for each ones or add the list of schema you want to exclude to SYSUSERS. The decision is much on how you want to work, sometime it is best to migrate schema per schema because there is no dependencies between them and sometime you are forced to migrate them at the same time.
