### ISSUE TITLE
Ora2PG - Does not convert dynamic sql

### ISSUE THREAD

**Issue by RuiFilipeGoncalvesPereira** [darold/ora2pg#1414]
Good Evening Darold,

I hereby get in touch because and I think you agree with me?, ora2pg does not convert dynamic sql from oracle to postgres, I have already installed the last version released on 02/10/2022, and I saw that even the last version does not include this functionality yet?

What I would like to know is whether ora2pg is expected to perform this conversion?, and if so, is there any expected date for this functionality to be included in ora2pg?

Best regards,

Rui Pereira.

**Comment by gilles-migops** [comment]
Right Ora2Pg doesn't convert string constant from dynamic SQL. The problem is that the SQL syntax can be totally broken by the dynamic part in the query construction and this could result in a complete store procedure broken translation. The best way to do that is to extract the query in a separate file and run ora2pg with the QUERY action to have a translation that you can replace in the code.

At this time I don't see a reliable way to translate dynamic SQL so I have no plan to work on it.
