### ISSUE TITLE
Global temporary tables

### ISSUE THREAD

**Issue by raqua** [darold/ora2pg#142]
Hello. 

I am using ora2pg 16.1 and it seems that when exporting tables, oracle global temporary tables are not exported. I tried searching ora2pg docs for this but I was not successful, so I am not sure if I do anything wrong or this is not supported.
Thanks

**Comment by darold** [comment]
Hello,

This is a normal behavior, global temporary table doesn't exist under PostgreSQL. A temporary table is always associated to the sesion that create this table, when the session closed the temporary table is removed.

I don't know what is the real use of this kind of object in your context, could you explain how you use it, so that we can try to find a solution.

Regards,

**Comment by raqua** [comment]
You are right, I wen't through PG docs now and PG does not have this feature. What we are usin in Oracle was global temp. table, that was persisted, but it's data were not. 
We will have to create this table each session. 
Thanks.
