### ISSUE TITLE
Missing commandline config option to import_all.sh

### ISSUE THREAD

**Issue by duursma** [darold/ora2pg#1436]
The import_all.sh uses commandline parameters to specify where to import all structural items.  For the data copy it fall back to the config/ora2pg.conf file which may have different information.  I think the import_all.sh should allow specifying which config files should be used.

**Comment by darold** [comment]
I'm not sure to understand,  import_all.sh must be run in the project directory so that it can find all DDL files generated by export_schema.sh  to import them from the right place. The path to configuration file is the same for both scripts config/ora2pg.conf , what is the usecase for an other configuration file for  import_all.sh?

**Comment by duursma** [comment]
I'm working on a huge (I think) case for which it is not clear what the end goal is.  For this I run into both structural issues and data issues.  I have therefor 2 databases.  In the first I try to see how far I can get loading types, tables, packages etc... and another I which I stop after loading tables and try to get the data loaded (currently stuck on geometries).  So I have two scripts calling import_all.sh with the right connection parameters.  But for one of them I can use the direct loading step.

**Comment by darold** [comment]
You should use an ora2pg dedicated command instead of using import_all.sh. You can run import_all.sh using the `-D` option to see what command to use.
