### ISSUE TITLE
Sequences not correctly migrated

### ISSUE THREAD

**Issue by jbouras** [darold/ora2pg#1438]
If the iseq_* are not migrated from oracle to postgres, how the current values for IDENTITY columns are set?

Using PG_VERSION 11 the auto increment sql script does not find any definition of sequence like:
nextval('schema.table_id_seq'::regclass)

**Comment by darold** [comment]
Identity columns are available since PG 10° so if you have PG_VERSION set to 11 when you have exported your table a file AUTOINCREMENT_output.sql might have been created. Once you have imported the table DDL you can load this script in psql to set the current value of the identity sequence.

If you have exported the table for a PG version < 10 it will use bigserial instead of an identity column. In this case the  AUTOINCREMENT_output.sql file is useless and as you said it doesn't detect the sequence and this is normal. I see what you are reporting, actually exporting sequences do not contain the Oracle identity for the corresponding bigserial sequence, I will fix that.

**Comment by jbouras** [comment]
I use postgres 11 and it generates AUTOINCREMENT with this script:
query := $$SELECT (string_to_array(adsrc,''''))[2] FROM pg_attrdef WHERE adrelid = '$$
                        || tbname || $$'::regclass AND adnum = (SELECT attnum FROM pg_attribute WHERE attrelid = '$$
                        || tbname || $$'::regclass AND attname = '$$ || colname || $$') AND adsrc LIKE 'nextval%'$$;

I think its not the the correct sql to find sequences for identity columns.

**Comment by darold** [comment]
Commit 8b73a50 might fix this issue.
