### ISSUE TITLE
Constraints with IS NOT NULL that are NOT VALIDATED are not correctly defined when using type TABLE

### ISSUE THREAD

**Issue by bensagar-ea** [darold/ora2pg#1546]
This line here in `sub _create_check_constraint`: https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg.pm#L10328

> `if ($chkconstraint =~ /^([^\s]+)\s+IS\s+NOT\s+NULL$/i)`

causes any check constraints that define `IS NOT NULL` conditions to be output as an `ALTER COLUMN` statement instead of `ADD CONSTRAINT` in this line: https://github.com/darold/ora2pg/blob/master/lib/Ora2Pg.pm#L10333

> `$out .= "ALTER TABLE $table ALTER COLUMN $col SET NOT NULL;\n";`

But if that constraint is `NOT VALIDATED` then this is not the correct behaviour and will cause the data to need to be made valid against this constraint on migration, which is not necessarily desirable. (It certainly isn't for me, where I'm trying to migrate data from Oracle to PostgreSQL including all its flaws and as close to its original definitions as possible.)

I can see that the approach of converting these constraints to `NOT NULL` on the column definition simplifies the resulting schema, but it does cause complications.

Having an exception put into the condition for the specific case where the constraint is `NOT VALIDATED` might cause confusing results, so perhaps this is something that could be controlled by a configuration setting?

A bit like the `PKEY_IN_CREATE` setting, something like `NOT_NULL_IN_COLUMN` (defaulting to `1`) that when set to `0` instead creates the constraint in the way that other check constraints are handled.

**Comment by darold** [comment]
- NOVALIDATE means that some existing data may not conform to the constraint
- ENABLE NOVALIDATE means that the constraint is checked, but it does not have to be true for all rows. This allows existing rows to violate the constraint, while ensuring that all new or modified rows are valid.

This "feature" is not possible with PostgreSQL and removing the NOT NULL constraints that are NOT VALIDATED is not correct as normally all new data must not be NULL. I think Ora2Pg has the correct behavior, if this is problematic for data import then the data must be fixed in Oracle or you can use the TRANSFORM_VALUE configuration directive. For example:
```
TRANSFORM_VALUE   TABLENAME[COLNAME:CASE colname WHEN NULL THEN '' ELSE colname END]
```
If you still think that the constraint should be removed then and ALTER command to remove the constraint is the solution.

**Comment by bensagar-ea** [comment]
Thank you @darold for the response and for looking into this.

> This "feature" is not possible with PostgreSQL and removing the NOT NULL constraints that are NOT VALIDATED is not correct as normally all new data must not be NULL

This feature is possible in PostgreSQL and can be expressed like this:

`ALTER TABLE table_name ADD CONSTRAINT constraint_name CHECK (column IS NOT NULL) NOT VALID;`

This is the output that ora2pg would produce if it wasn't for that line that explicitly changes a table-level CHECK constraint from the Oracle database into a column-level SET NOT NULL statement in the PostgreSQL script.

I can see that doing this makes the script a bit neater, but it does create a constraint that is different from the one in the source Oracle database. That seemed like incorrect or at least undesirable behaviour.

In the end I resolved this by generating my own script for these constraints and applied it after loading the data, so no harm done. It just took me quite a while to discover why my data wasn't loading, so I thought I'd share my discovery (and a potential fix) in case it saved anyone else having the same issue.
