### ISSUE TITLE
Issue in DDL for SYNONYM from Oracle as it consist object names with full classified name

### ISSUE THREAD

**Issue by priyanshi-yb** [darold/ora2pg#1578]
While exporting the SYNONYM from oracle the VIEW DDLs have the some other objects in `select` statement on which the view is created and those objects contain the full object name including schema-name same as Oracle. 
Example - 
DDL used on Oracle on Schema TEST:
```
CREATE OR REPLACE SYNONYM offices for locations;
```
Exported DDL: 
```
CREATE OR REPLACE VIEW offices AS SELECT * FROM test.locations;
```

Thanks for the help in advance.

**Comment by darold** [comment]
Commit 047f73e fixes this issue.

**Comment by coldserenity** [comment]
Hello, @darold 
Sorry for jumping in on a closed defect. From what I understand, this change modifies owner/schema prefix addition to only happen in the following combination of parameters

- the synonym has a table_owner 
- AND no specific schema was set with --schema or SCHEMA config
- AND EXPORT_SCHEMA=1 is set 

Now imagine a use-case: I have 20+ Oracle schemas to export, so I export them one-by-one in a shell script with --schema option, because ora2pg does not support mult-schema export. This effectively disables my ability to preserve where each object comes from, and thus the ability to re-create the database. I have synonyms in one schema referencing tables and views in the other. But now there is no combination of parameters that would allow me to keep the original schema name for my use-case. Or is there? 

With regards,
  Roman
