### ISSUE TITLE
Column named with Postgresql reserved words convert incorrectly from Oracle

### ISSUE THREAD

**Issue by alexign** [darold/ora2pg#162]
Hello!
In Oracle I have table with column named **limit** . After ora2pg conversion it convert to column named **limit** which leads to error while table creation:

ERROR: syntax error at or near "limit"

I think we need to escape columns named with Postgres reserved words with double quotes. i.e:
oracle column name **limit** -> postgres column name **"limit"**

**Comment by darold** [comment]
Hi,

The easiest way is to rename your column and modify your application, otherwise you will also need to modify your application to add the doublequote in your queries.

If you want to keep those reserved name, then enable the USE_RESERVED_WORDS configuration directive in ora2pg.conf

Best regards,

**Comment by alexign** [comment]
Oops! Missed this param too , sorry and thank you!

Sent from Outlook Mobile




On Thu, Feb 11, 2016 at 8:37 AM -0800, "Darold" <notifications@github.com> wrote:












Hi,



The easiest way is to rename your column and modify your application, otherwise you will also need to modify your application to add the doublequote in your queries.



If you want to keep those reserved name, then enable the USE_RESERVED_WORDS configuration directive in ora2pg.conf



Best regards,

**Comment by darold** [comment]
That's ok, there is around 90 configuration directives with Ora2Pg, I used to forgot some of them too.
