### ISSUE TITLE
need some hint w.r.to ver 24.0 and the usage of MSSql Server to Postgresql Conversion

### ISSUE THREAD

**Issue by bharanisvng** [darold/ora2pg#1662]
Team
Need need some hint w.r.to ver 24.0 and the usage of MSSql Server to Postgresql Conversion
a) what is the command syntax for generating assessment report - ms sql server to postgresql
-M is not working
if detailed documentation is available, can u please share it

b) how to generate DDL's Dump using MS Sql Server

**Comment by darold** [comment]
Hi,

First, please use latest development code I have fixed several MS SQL DDL export since the last release.

a) what is the command syntax for generating assessment report - ms sql server to postgresql
-M is not working

This is the same as for Oracle: `ora2pg -c config/ora2pg.conf -t SHOW_REPORT` the source database type is auto-detected from the ORACLE_DSN value. Supposing that you have the right connection string.

b) how to generate DDL's Dump using MS Sql Server
I don't know how to do that in SQL Server and also this is not the right place to ask help on SQL Server.

**Comment by bharanisvng** [comment]
a) as suggested , we have downloaded Development code and were testing MS SQL Server to Postgresql migration using ora2pg - dev version                                                                                                                                                           
                          ora2pg-master>ora2pg -t SHOW_REPORT -c ora2pg.conf -M dbi:ODBC:Driver="test2"  > report1.html
DBI connect('Driver=test2','sa',...) failed: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (SQL-IM002) at C:/Strawberry/perl/site/lib/Ora2Pg/MSSQL.pm line 76.
 receiving the above said error. We confirmed the standalone ODBC driver is working correctly

b) regarding other question , need to know how to generate the postgres converted ddl for sql server as source by ora2pg.
