### ISSUE TITLE
Bad handling of user defined PATHs

### ISSUE THREAD

**Issue by saspg** [darold/ora2pg#181]
Hello, 

When trying to fine tune ora2pg installation, I get a weird paths configuration.
I want to define paths that don't begin by /usr/local or /opt, but it seems that whenever PREFIX does not begin by /usr/local or /opt, CONFDIR and DOCDIR are hard defined.
That make them be really different from expectations.

Version of ora2pg is HEAD (17.3 as stated in changelog).

Here is a short example and how to reproduce it:

[sas@machine ora2pg-master]$ perl Makefile.PL PREFIX=/some/personal/directory/ora2pg CONFIDR=etc DOCDIR=doc
[sas@machine ora2pg-master]$ tail Makefile
        @echo "Installing default configuration file (ora2pg.conf.dist) to /some/personal/directory/ora2pg/etc/ora2pg"
        @$(MKPATH) /some/personal/directory/ora2pg/etc/ora2pg/ora2pg
        @$(CP) -f ora2pg.conf.dist /some/personal/directory/ora2pg/etc/ora2pg/ora2pg/ora2pg.conf.dist
        @$(MKPATH) /some/personal/directory/ora2pg/usr/share/doc/ora2pg
        @$(CP) -f README /some/personal/directory/ora2pg/usr/share/doc/ora2pg/README
        @$(CP) -f INSTALL /some/personal/directory/ora2pg/usr/share/doc/ora2pg/INSTALL
        @$(CP) -f changelog /some/personal/directory/ora2pg/usr/share/doc/ora2pg/changelog

I would have expected:
 @echo "Installing default configuration file (ora2pg.conf.dist) to /some/personal/directory/ora2pg/etc/ora2pg"
        @$(MKPATH) /some/personal/directory/ora2pg/etc
        @$(CP) -f ora2pg.conf.dist /some/personal/directory/ora2pg/etc/ora2pg.conf.dist
        @$(MKPATH) /some/personal/directory/ora2pg/doc
        @$(CP) -f README /some/personal/directory/ora2pg/doc/README
        @$(CP) -f INSTALL /some/personal/directory/ora2pg/INSTALL
        @$(CP) -f changelog /some/personal/directory/ora2pg/doc/changelog

Thanks.
SAS

**Comment by darold** [comment]
Thanks for the report, last commit 92567d0 might fix the Makefile.

**Comment by saspg** [comment]
I'm afraid you've lost the part where you concatenate ($PREFIX and $CONFDIR), and ($PREFIX and $DOCDIR) when $CONFDIR and/or $DOCDIR are defined.

**Comment by darold** [comment]
There was still an issue when creating the configuration directory fixed in last commit, but yes I removed the concatenate part to simplify the code.

You have to use absolute path if you want to rebase the configuration and documentation directories. For example your configure command:

    perl Makefile.PL PREFIX=/some/personal/directory/ora2pg CONFIDR=etc DOCDIR=doc

might be written:

        perl Makefile.PL PREFIX=/some/personal/directory/ora2pg CONFIDR=/some/personal/directory/ora2pg/etc DOCDIR=/some/personal/directory/ora2pg/doc

or in this case simply

    perl Makefile.PL PREFIX=/some/personal/directory/ora2pg

because etc/ and doc/ are the default subdirectory.

But I'm agree that when a relative path is used, the prefix should be concatenate, I will fix that later.

**Comment by darold** [comment]
Last two commits allow use of relative path to PREFIX with CONFDIR and DOCDIR.

**Comment by saspg** [comment]
Many thanks for your reactivity!

**Comment by saspg** [comment]
I'm afraid there are some quirks left within Makefile.

Indeed, all installation directories are created by concatenation between DESTDIR and some hardcoded pathes, i.e. 
INSTALLARCHLIB = /usr/lib64/perl5
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)

That lead to /some/personal/directory/ora2pg/usr/lib64/perl5

Which is quit annoying.

BTW, PREFIX here is defined as "/usr/local/" and DESTDIR is defined to the value passed as argument to Makefile.PL


Same with 
INSTALLSITEBIN = /usr/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
Which leads to have ora2pg installed in /some/personal/directory/ora2pg/usr/local/bin/

Last but not least, how can I declare a different PATH for the perl to use. System wide perl installation is outdated, so last perl version as been installed in a custom directory, which ora2pg can't guess by itself.

**Comment by darold** [comment]
This is the Perl Makefile.PL have to install Perl libraries. In fact DESTDIR and PREFIX are aliases to Perl environment variable INSTALL_BASE. INSTALL_BASE tells ora2pg installer to put the modules into  /some/personal/directory/ora2pg/usr/lib/perl5 or /some/personal/directory/ora2pg/usr/local/lib/perl5, but this path is dependent of your distribution. For you it is $INSTALL_BASE/usr/lib64/perl5 because in your distribution this is the default path for the site perl install dirs. If you want to install into /usr/local/lib64/perl5 you may try to set environment variable  INSTALLDIRS to vendor.

To use the libraries installed into /some/personal/directory/ora2pg/usr/lib/perl5 or other non default path, just set PERL5LIB to that path and ora2pg will find the lib.

To use a different version of perl binary you can just call ora2pg with this perl version, ex:

    /home/user/Perl5/bin/perl  /some/personal/directory/ora2pg/bin/ora2pg ....

this might works.

Using perlbrew is also a good alternative but not as simple as above solution.

**Comment by saspg** [comment]
Gilles, 

Thank you for your answer.
Will try that.

S.

**Comment by darold** [comment]
Please Stephane, have a look to latest commit on Makefile.PL, there is some change related to RPM packaging compatibility that was addressed in issue #180 . This may change the behavior explained above.
