### ISSUE TITLE
missing foreign keys

### ISSUE THREAD

**Issue by raulcejas04** [darold/ora2pg#1831]
I generate the script all_export.sh and it doesn't create the foreign keys.

all_export.sh creates all ddl: create tables, unique indexes, indexes, and null constraints but not foreign keys.

If I run ora2pg -t TABLE -d -o ddl.sql -b ./ -c /etc/ora2pg/ora2pg.conf I get the same result: missing foreign keys.

what is wrong? is it a bug?

**Comment by darold** [comment]
There must be a file name FKEYS_ddl.sql in the schema/tables/ sub directory, it it is not present that could mean that there is no foreign keys defined. Can you confirm that the file is generated or not? Also what is the value of SKIP in the configuration file?

**Comment by raulcejas04** [comment]
Hi, thank you for your answer. In schema/tables subdirectory I don't have FKEYS_ddl.sql file

This is the contents of my configuration file:

RACLE_HOME /opt/oracle/instantclient_21_15
ORACLE_DSN dbi:Oracle:host=myhost;service_name=myservice;port=1521
ORACLE_USER user
ORACLE_PWD passw
USER_GRANTS 1
TRANSACTION READONLY
EXPORT_SCHEMA 1
SCHEMA MULTAS
FILE_PER_TABLE  1
USER_GRANTS 1

An the oracle schema has foreign keys.

**Comment by raulcejas04** [comment]
Please see https://www.linkedin.com/pulse/quick-easy-guide-use-ora2pg-windows-seyed-ibrahim/ it seems the error is not new

"Foreign keys aren't created, as you could see from the above samples."

**Comment by darold** [comment]
Actually this was not related to windows but from file input. Commit e848289 fixes this issue.

**Comment by omolenkamp** [comment]
I'm having the same problem as @raulcejas04, and I don't think e848289 fixes it. That commit fixes something with parsing an input file, which we don't use.

Since version 24.2, the `FKEYS_` file is no longer written, unless `PG_VERSION` is set to a version higher than 12. This is caused by this line in `_create_foreign_key`:

```
next if ($self->{pg_supports_partition} && exists $self->{partitions_list}{lc($desttable)} && $self->{pg_version} <= 12);
```

I don't use partitions in Oracle, but because of a change in 24.2, `$self->{partitions_list}{lc($desttable)}` now always seems to contain a reference to a (possibly empty) hash, which causes this `next` statement to skip all foreign keys on versions before 13.

Either there should not be a hashref for unpartitioned tables in `partitions_list`, or this check should be fixed to look at the contents/size of the hash, instead of merely looking at its existence.
