### ISSUE TITLE
Problem with table named "partition"

### ISSUE THREAD

**Issue by pavelmakarov** [darold/ora2pg#193]
Hi,

I've faced the following issue during migration.

The table named "partition" (sad but true) couldn't has been created correctly on PG due to keyword "partition" is reserved for other purposes. Table name appears in scripts and causes runtime syntax error.
I've tried to surround table name with commas then module Ora2PG.pm failed:

> DBD::Pg::db do failed: ERROR:  syntax error at or near "partition"
> LINE 1: ALTER TABLE partition DISABLE TRIGGER USER;
>                     ^ at /usr/local/share/perl5/Ora2Pg.pm line 4646.

Is there are any workaround for this?

Regards, Pavel

**Comment by darold** [comment]
Hi,

You have at least two possibility. The first one is to replace this table name on the fly using:

    REPLACE_TABLES    PARTITION:t_partition
you will be able to export the table and the corresponding data into the table t_partition or any name you choose.

The second solution is to enable USE_RESERVED_WORDS,  Ora2Pg will always use double quote with the tablename.

I recommend you the first solution because in both case you will need to edit your scripts.

Regards,
