### ISSUE TITLE
facing problem with ORA-24345: A Truncation or null fetch error occurred

### ISSUE THREAD

**Issue by walpino** [darold/ora2pg#194]
I did this migration some weeks ago 
and there were no problems
now I'm facing a problem like the following

[root@chbo1srv116 homegate_migration_prod_bigtables]# ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg_data_hist.conf
[========================>] 1/1 tables (100.0%) end of scanning.
DBD::Oracle::st fetchall_arrayref failed: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 3 of 258, ora_type 1) [for Statement "SELECT "REF_PROPERTY","REF_HOUSE","REF_OBJECT","PUBLISHING_GROUP_ID"....ENERGY_DOC_FILENAME_ORIG_2" FROM "xxx" a WHERE (TIME_STAMP < '2016-05-23')"] at /root/perl5/lib/perl5/Ora2Pg.pm line 9958.
ERROR: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 3 of 258, ora_type 1)
[========================>] 21290000/21290000 rows (100.0%) Table IMMOPOOL_HISTORY (4446 sec., 4788 recs/sec)
[========================>] 21290000/21033059 rows (101.2%) on total estimated data (0 recs/sec)
[========================>] 21290000/21033059 rows (101.2%) on total estimated data (4447 sec., avg: 4787 tuples/sec)

I alread extended the value of 
LONGREADLEN     100000000
but this doesn't help

are there any other reason for this Problem ?

**Comment by darold** [comment]
Hi,

Please use latest development code or the latest official release 17.4 and report the new error message. Here at line 9956 in Ora2Pg.pm there's no call to the fetch method.

Best regards,

**Comment by walpino** [comment]
I upgrade to the Version 17.4
but I still get this error
any ideas?

[root@chbo1srv116 homegate_migration_prod_bigtables]#  ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg_data_hist.conf
[========================>] 1/1 tables (100.0%) end of scanning.
DBD::Oracle::st fetchall_arrayref failed: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 3 of 258, ora_type 1) [for Statement "SELECT "REF_PROPERTY","REF_HOUSE","REF_OBJECT","PUBLISHING_GROUP_ID"....ENERGY_DOC_FILENAME_ORIG_2" FROM "xxx" a WHERE (TIME_STAMP < '2016-05-23')"] at /root/perl5/lib/perl5/Ora2Pg.pm line 10280.
ERROR: ORA-24345: A Truncation or null fetch error occurred (DBD ERROR: ORA-01406 error on field 3 of 258, ora_type 1)
[========================>] 21290000/21290000 rows (100.0%) Table IMMOPOOL_HISTORY (3838 sec., 5547 recs/sec)
[========================>] 21290000/21033059 rows (101.2%) on total estimated data (0 recs/sec)
[========================>] 21290000/21033059 rows (101.2%) on total estimated data (3839 sec., avg: 5545 tuples/sec)

**Comment by darold** [comment]
Can you, please, send me the description of the table? If you need privacy, send it to my private email gilles AT darold DOT net

Kind regards,

**Comment by darold** [comment]
Hi,

I don't think the issue comes from the LONGREADLEN value, you don't have any LOB object in this table so the default value must be enough. The second error message reported by Oracle: "ERROR: ORA-01406 error on field 3 of 258, ora_type 1" look like a data type internal format problem. The error occurs on the third column that is defined as a VARCHAR2(80 BYTE) NOT NULL but I think you have made a binary upgrade of your data and the type have changed between the two database version. Something like in the report: http://siebelunleashed.com/truncation-or-null-fetch-error-occurred/

I'm afraid that this is an Oracle issue. What you can try is to enable LOG_ON_ERROR in ora2pg.conf and try to find what tuples are affected by this problem. On error, Ora2Pg will continue to try to fetch new DATA_LIMIT bulk of data. Adjust the WHERE clause and the DATA_LIMIT value (see ora2pg option -L) to try to find the affected data.   Or you can use some query like "SELECT dump(COL3) FROM MYTABLE WHERE ..." to look at the internal storage information and find the reason of the issue.

Let me know.

**Comment by walpino** [comment]
Hi there
I changed the value of LOG_ON_ERROR               1
but I see no outputerror file

this is how I start the job

ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg_data_hist.conf

Thanks

2016-05-26 9:28 GMT+02:00 Darold <notifications@github.com>:

**Comment by darold** [comment]
Ok that mean that the error appears immediatly and Oracle doesn't return any rows. As I said, this is an Oracle internal type issue on your third column. You must try to identify the lines that have this corruption. If you can made an SQL export of the table using and other tool, recreate a new identical table and import data with the SQL import, Ora2Pg should be able to export the data from the new table. Otherwise the database corruption is worst.

**Comment by walpino** [comment]
Hi
I exported the rows and inserted them in a new table
no problem

but the truncation is still happening on the new table

i guess I have to do some research more

but there is still a strange thing

the values in this table are the same as the values on other tables
and the other tables can be migrated to postgres



Thanks

Martin

2016-05-26 22:43 GMT+02:00 Darold <notifications@github.com>:
