### ISSUE TITLE
Deferring foreign key constraints in direct Pg mode

### ISSUE THREAD

**Issue by SebAlbert** [darold/ora2pg#199]
When COPYing data in direct Pg mode, the SQL statement telling Postgres to DEFER the foreign keys happens inside a transaction and is followed by a COMMIT _before_ the actual COPYing of data happens, so the foreign keys are in fact not deferred, which results in FK violation errors for me.

(I could have worked around this issue in my case if either the tables were processed in the same order as they are stated in the ALLOW configuration or if the restauration after COPYing with DROP_FKEY 1 from MySQL would work properly (see #198), but still this seems to be an issue on its own.)

**Comment by barabaka** [comment]
I experience the same problem with the following config
TYPE TABLE,COPY
FKEY_DEFERRABLE 1
DEFER_FKEY 1

Foreign key constraints are created as DEFERRABLE INITIALLY DEFERRED -- this part looks correct.
But when importing data I am getting FK constraint errors.

**Comment by darold** [comment]
Hi,

Last commits change this behavior removing the possibility to use of DEFER_FKEY with direct import to PostgreSQL. It will now print a fatal message and a hint to check use of DROP_FKEY instead.

With all design change since this feature exists, it is not more possible to defer foreign keys with direct import because we create a new connection to PG for each process dedicated to data import, even if multiprocess is not used.

By the way it is always a good idea to not import constraint and index before data import to improve migration speed. If this is not possible, you must enable DROP_FKEY, this will drop all concerned foreign keys before data import and recreate them when all data import are terminated.

Best regards,
