### ISSUE TITLE
Wrong conversion oracle-type "Number" to "Bigint"

### ISSUE THREAD

**Issue by aleksaan** [darold/ora2pg#200]
In case of field has a number-type conversion is wrong. 
When field has a number(12) type conversion is correct.

**Comment by darold** [comment]
Hi,

NUMBER() without precision are converted to bigint by default because most of the time it is used as column type for the unique id. If this is not the case in your database you can change this behavior by using DEFAULT_NUMERIC or PG_INTEGER_TYPE configuration directive.

Regards,

**Comment by aleksaan** [comment]
Hi, Darold
I disagree with that defaults-settings. In the first place, defaults must ensure a correct conversion between databases and in second place a preferences of users (by additional settings).  But you are author and you should decide.

**Comment by darold** [comment]
I agree with you, but the problem is that if we use numeric() by default all the unique keys will be of internal type varlena and  you will loose some performances. In my opinion and experiences, identifying fields that need to be numeric() takes less time than change the type of all unique keys. The user that make an Oracle to PostgreSQL migration need to take care of that, Ora2Pg is not a one click tool that makes decision for you, you have to know what you are doing and what you have to take care.

**Comment by aleksaan** [comment]
Ok, thanks for your comments !  It looks like right point of view.

**Comment by kuzmaka** [comment]
Hi, 
I agree NUMBER() to bigint conversion is a good default heuristic. Also I think it would be better to convert NUMBER(*, 0) to bigint instead of numeric(38, 0) by default.
