### ISSUE TITLE
ORA-01555: snapshot too old

### ISSUE THREAD

**Issue by swvanlinge** [darold/ora2pg#209]
When trying to export certain tables from Oracle 11gR2 into a table with INSERT statements, I frequently get snapshot too old errors despite the tables often being relatively small segments (< 1GB) and the UNDO space being > 40G.  I've scoured the config file for notes about this and your issues forum as well as Google over the past 3 weeks but I can't find anything related.  Is this an active issue?  Is there a workaround?  Any config settings I could tweak to make this occur less often at least?  I've used this tool with past projects and it was flawless, but with this database for some reason there are just so many issues with data conversion.

Added:  I should also note that I have data_limit set to 100, transaction to readonly, bloblimit set to default, and longreadlen set to 10000000.  On our production database, we usually have around 3 days of undo.  However, I'm running ora2pg on a copy of production (from Dataguard) with no user activity on it whatsoever and the same UNDO size.

**Comment by darold** [comment]
Hi,

You might first use COPY instead of INSERT, this will considerably improve data import speed into PostgreSQL. INSERT export type is only provided if you need compatible insert statement. DO NOT use INSERT if you want to migrate your data into PostgreSQL and especially with direct import because you will also slow down data export from Oracle.

I don't know the amount of memory on the Ora2Pg machine, but I think you can use 10000 for DATA_LIMIT and set BLOB_LIMIT to 100.

If you still have the snapshot too old error after those changes, this is an issue related to the MVCC implementation of Oracle. Increasing your UNDO might solve the issue. You can also set TRANSACTION to committed in ora2pg.conf if you don't have any connection and modification into the database during the migration, otherwise you will have some consistency troubles.

Best regards,

Reminder: DO NOT use INSERT to migrate your Oracle data into PostgreSQL !

**Comment by swvanlinge** [comment]
There's 16GB on the migration machine.  I'm trying all the settings you recommended.  Thanks for the quick reply, I'll close this as soon as it's done testing.

**Comment by swvanlinge** [comment]
This fixed the snapshot too old errors.  Thank you!
