### ISSUE TITLE
Wrong conversion of INTEGER data type

### ISSUE THREAD

**Issue by dezdechado** [darold/ora2pg#210]
Let we have table in Oracle DB:
`CREATE TABLE TEST_TABLE
(
  FIELD_1  INTEGER,
  FIELD_2  NUMBER
)`
I expect it to be converted ( with PG_NUMERIC_TYPE=1,  PG_INTEGER_TYPE=1, DEFAULT_NUMERIC=NUMERIC) as:
`CREATE TABLE test_table (
	field_1 bigint,
	field_2 NUMERIC
)`
But I've got:
`CREATE TABLE test_table (
	field_1 NUMERIC,
	field_2 NUMERIC
) `
INTEGER is NUMBER with data_length==38, precision == null and scale == 0. As far as I can understand from Oracle documentation, that means that precision==38 as well as length. But it doesn't handled in procedure `_sql_type` in Ora2Pg.pm. Maybe, it can be fixed with something like:
`if ( $type eq 'NUMBER' ) {
		if ( ($scale ne '') && ($precision == 0) ) {
			$precision = $len;
		}
}`

**Comment by darold** [comment]
It seems that for a NUMBER with a DATA_SCALE set to 0, no DATA_PRECISION and a DATA_LENGTH of 22 in ALL_TAB_COLUMNS, Oracle use a NUMBER(38) instead. This correspond to Oracle type INTEGER or INT. I don't really understand the reason of this particularity, why not just using a data length of 38? ALL_TAB_COLUMNS and Ora2Pg reports a data length of 22, now Ora2Pg will report NUMBER(38) like the resulting type of the DESC command.

The following Oracle table:
```
CREATE TABLE TEST_TABLE ( FIELD_1 INTEGER, FIELD_2 NUMBER );
```
will be exported as follow by Ora2Pg:

```
[1] TABLE TEST_TABLE (owner: HR, 0 rows)
	FIELD_1 : NUMBER(38) => numeric
	FIELD_2 : NUMBER(22) => bigint
```

Oracle data type INTEGER and INT will be exported as numeric by default now instead of integer.

See commit bd4664b

Of course if you want to export NUMBER without precision and scale to numeric, you still have to set DEFAULT_NUMERIC to numeric.

Best regards

**Comment by dezdechado** [comment]
Well, I can just assume that DATA_LENGTH is not the maximum number of digits in a number, but the maximum number of bytes of it's inner representation (of course, numbers can be stored more compact than byte per digit). Hence, I think, you are right. DATA_LENGTH should't be used and data_precision = 38 according to the documentation. My mistake.
I will check your commit. Thanks!

**Comment by dezdechado** [comment]
Hm. So, now INTEGER will be always treated as NUMERIC? Is there any way to change this behavior?

**Comment by darold** [comment]
Yes this is the right conversion type even if most of the time bigint may be enough. If you want to change the conversion type you need to redefined NUMBER(38) and not INTEGER with the DATA_TYPE configuration directive.
```
DATA_TYPE       NUMBER(38):bigint
```

for example, SHOW_COLUMN will return:
```
gilles@devel:$ ora2pg -c config/ora2pg.conf  -t SHOW_COLUMN -a PEOPLE
[1] TABLE PEOPLE (owner: ADM, 2 rows)
	ID : NUMBER(38) => bigint
	OBJ : PERSON(256) => PERSON
----------------------------------------------------------
Total number of rows: 2
```

Is that what you are looking for?

**Comment by dezdechado** [comment]
Yes, thanks!
Just one more question.  Why will be integer exported as numeric by default? Why not numeric(38)?

**Comment by darold** [comment]
Why not numeric(38)? Surely the thing with me for so long, I mean stupidity. Commit c8af805 solves this.

Thanks

**Comment by dezdechado** [comment]
Great, thanks!
