### ISSUE TITLE
tranformation `SELECT INTO` into `SELECT INTO STRICT` is not robust

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#257]
Sometimes this transformations is not processed:
Oracle:
<pre>
         IF mStejnyIndex = 'A' THEN
            BEGIN
              SELECT ID_VYNDEV INTO mID_VYNDEV_AKT
               FROM VYVVYRVYN
                 WHERE ID_VYROK = mID_VYROK
                 AND ROWNUM < 2;
</pre>
Postgres:
<pre>
          IF mStejnyIndex = 'A' THEN
            BEGIN
              SELECT ID_VYNDEV INTO mID_VYNDEV_AKT
               FROM VYVVYRVYN
                 WHERE ID_VYROK = mID_VYROK
                 LIMIT 1;
</pre>

**Comment by darold** [comment]
Ora2Pg will add a STRICT after INTO only if an excpetion with NO_DATA_FOUND or TOO_MANY_ROW is present in the PL/SQL code. Using this code with such an exception the rewriting works.

**Comment by okbob** [comment]
I don't understand to this logic - Oracle raises a exception although it is not handled in a same procedure. Usually it is handled and reraised due better error message and possibility to get some info, but it it isn't handled explicitly, then this exception stops a procedure execution.

**Comment by darold** [comment]
In your query above the Oracle query can return 0 or 1 tuple (ROWNUM < 2), Ora2Pg translate it into LIMIT 1 so that it will also return 0 or 1 tuple. This is exactly the same and no exception are fired on both side. Oracle doesn't have the STRICT behavior natively and if you want the same feature you have to create the following clause in the PL/SQL code:
```
ÈXCEPTION
    WHEN TOO_MANY_ROWS
        -- do something
    WHEN NO_DATA_FOUND
        -- do something else
...
```
so Ora2Pg look for this kind of block and if one is found it adds the STRICT keywords.

Looking at the Or2Pg code I see a bug that can lead to adding STRINCT to the wrong SELECT queries. I will fix it.

**Comment by okbob** [comment]
OK - what I read in documentation - TOO_MANY_ROWS can raise a exception - but it has not sense if there is LIMIT, NO_DATA_FOUND raises a warning, that is not propagated out of function. I have to check the behave on Oracle.
