### ISSUE TITLE
Table with $ character

### ISSUE THREAD

**Issue by liemdt1811** [darold/ora2pg#362]
Hi Darold,
I have table aud$ on schema abc in Oracle
The export table.sql script is create table "abc.aud$" which become a table name "abc.aud$" not aud$ in schema abc.
This also happen in indexes, constraints, etc. 
Then I have to remove the double quote in these scripts.

My configuration are:
SCHEMA (blank)
PG_SCHEMA (blank)

Hope you can fix it.

Regards,
LiemDT1

**Comment by darold** [comment]
Hi,

Most of the time object with a $ are system oblject that must not be exported. Can you confirm this affirmation or do you really need to export this kind of object? If this is a system object, please give us the real schema+object name so that I will exclude it from export.

Otherwise, commit dffe6e8 might solve your issue.
