### ISSUE TITLE
`INTO STRICT` should be used everywhere

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#412]
It was a new for me (but I am not Oracle expert) . Minimally in PL/SQL the Oracle is very restrictive:

Just simple procedure:
<pre>
create or replace procedure A1_B1 is
  mID_CCLE CLEOSOBY.ID_CCLE%type;
begin

  SELECT ID_CCLE INTO mID_CCLE
     FROM CLEOSOBY

      where  id_ccle = -1;
end A1_B1;

Result when there are no rows:
*
ERROR na řádku 1:
ORA-01403: nenalezena žádná data
ORA-06512: na "PRETEST.A1_B1", line 5
ORA-06512: na line 1
</pre>

Update for more rows:
<pre>
create or replace procedure A1_B1 is
  mID_CCLE CLEOSOBY.ID_CCLE%type;
begin

  SELECT ID_CCLE INTO mID_CCLE
     FROM CLEOSOBY  ;
end A1_B1;

BEGIN a1_b1(); END;

*
ERROR na řádku 1:
ORA-01422: přesné načtení vrací více než požadovaný počet řádek
ORA-06512: na "PRETEST.A1_B1", line 5
ORA-06512: na line 1
</pre>
So now it looks like INTO STRICT should be used everywhere.

**Comment by darold** [comment]
Right, this is new for me too.

**Comment by darold** [comment]
Actually Ora2Pg only append the STRICT keyword when an exception block contain NO_DATA_FOUND or TOO_MANY_ROW, if I remember well this was because I want to be sure that no other SELECT + INTO was affected by this change. But I agree that when the exception block is not present STRICT should be appended too as unlike in plpgsql SELECT INTO is not used for variable affectation.

**Comment by darold** [comment]
And then commit f4b8e5e applies this behavior.

**Comment by okbob** [comment]
It is fixed, thank you
