### ISSUE TITLE
ora2pg-18.1 - possible bug

### ISSUE THREAD

**Issue by venkatabn** [darold/ora2pg#436]
Hi,

I have been using ora2pg to migrate the data from Oracle to PostgreSQL and i have been encountering following issues -

- If you can see the output messages below, ora2pg wrongly interprets the number of rows to be migrated. The data migration works fine. 
[========================>] **65/64** rows (**101.6%**) Table xxx_xxx_xxxxx (2 sec., 32 recs/sec)
[========================>] **55747/55563** rows (100.3%) Table xxx_xxx (25 sec., 2229 recs/sec)
[========================>] **205697/203916** rows (**100.9%**) Table xxx_xxx_xxx(57 sec., 3608 recs/sec)
[========================>] **261509/259543** rows (**100.8%**) on total estimated data (58 sec., avg: 4508 tuples/sec)

The other question i have is that, if ora2pg can migrate the data in parallel for bigger tables ?

Regards,
Ven.B

**Comment by darold** [comment]
Hi,

If you want ora2pg to use the "right" number of row refresh the statistic because ora2pg doesn't use count() but get the information from Oracle statistics. 

To migrate data in parallel mode you can use the `-P n` command line option, but if you have one big table to migrate in parallel, see `-J n` or ORACLE_COPIES configuration directive to have more information.

Regards,
