### ISSUE TITLE
Oracle views not being exported

### ISSUE THREAD

**Issue by Gyoo** [darold/ora2pg#492]
Greetings,

I am using Ora2PG to migrate from an Oracle 9i database to a PostgreSQL 9.3 database.
The source database has around 350 views. However, when I try to export these with a standard conf file (No ALLOW or EXCLUDE items), only ~260 views are exported.
I have no idea why almost a hundred views are ignored in the export. I don't think it is a grant issue, since when I'm using my db client with the same user as for the export, I can access all the views correctly.
I tried running with debug mode on, but it doesn't give me more info about why the views are ignored. They're just not there...

Best regards,
Gyoo.

**Comment by okbob** [comment]
Are these views compiled? I had some issues with broken/uncompiled objects.

**Comment by darold** [comment]
Yes, you can ask Ora2Pg to force compile the schema before looking for objects, this is especially recommended after a fresh import.  Set COMPILE_SCHEMA to 1 in your ora2pg.conf.

After that if the views are still marked invalid by Oracle perhaps they are not used by your application and so they don't have to be translated. This is something common. Otherwise set EXPORT_INVALID to 1 to force Ora2Pg to export all invalid object but it is better to fix them on Oracle first and make the valid.

**Comment by Gyoo** [comment]
From the looks of it this is the actual solution. After recompiling the views manually I was able to extract them correctly. A few views fail to compile, but that's my own problem.

I'll give the COMPILE_SCHEMA configuration a try tomorrow, but I think I'm pretty much set from now. Thanks both of you for your help.
