### ISSUE TITLE
is it possible to split a single table export into multiple output files

### ISSUE THREAD

**Issue by seadba** [darold/ora2pg#502]
hello, i have a 400M row table with a clob - currerntly running a INSERT type export - at the moment 90M rows have been exported - my tmp file is 360G - so potentially a 1.2T file - i see the FILE_PER_TABLE setting but i assume that is for full export - is there a way to split a single table export into multiple files?thanks

**Comment by darold** [comment]
Hi,

First of all do not use INSERT export type unless you don't want to import data into a PostgreSQL datavase, it will takes days to load 400M of rows. Use COPY export type instead.

To answer to your question, no there is no way to export a single table into multiple files. But at this level using files is not a good thing, you might want to import data directly to PostgreSQL (see PG_DSN) and use multi-process. For this kind of table, for example if you have 24 cores on your server, use -J 8 -j 4 command line options together with direct import to PostgreSQL will help you to save lot of time during the migration. I don't know if using INSERT and export into file is mandatory for you but if you continue in this way you will cry at file import time unless you have a week to loose.

If you have lot of RAM you can also increase the value of DATA_LIMIT (default to 10000) this will help a lot to save export time. What is the system resources on the Ora2Pg machine?

**Comment by seadba** [comment]
hello, thanks for update
64G Mem
12 processor

the full INSERT with excluded columns took 17hrs to extract 464M rows - could i use modify_struct with a direct import?

**Comment by darold** [comment]
Ok, it takes 17 hours to export into file but it will take more to load into PostgreSQL.

Yes MODIFY_STRUCT is especially done for data migration.  If I was you I would try to load data directly into PostgreSQL using the following command:
```
ora2pg -c config/ora2pg.conf -t COPY -a MY_HUGE_TABLE_NAME -J 4 -j 2 -L 50000
```
If the export fail due to OOM, use `-L 25000` instead, otherwise you can try to increase the number of parallel processes and the DATA_LIMIT (-L option). The more processors and memory you have, the speedier your data migration can be done.

Of course it is better to import indexes and constraint after data are loaded. You will be able to import indexes and constraint using parallelism too if PG_DNS is set. For example:
```
ora2pg -c config/ora2pg.conf -t LOAD -i schema/tables/INDEXES_table.sql -j 8
ora2pg -c config/ora2pg.conf -t LOAD -i schema/tables/CONSTRAINTS_table.sql -j 8
```

**Comment by darold** [comment]
Please, add feedback about the timings of your data migration and the parameters used.

**Comment by seadba** [comment]
sure - we have several large tables so we will be testing for some  time - i appreciate the fast and helpful assistance - will update as we go
thanks again
