### ISSUE TITLE
the replecement to_char by cast to varchar should be optional

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#513]
Orafce has own implementation of to_char(arg). There is support for session date format, and for some cleaning on Numeric type. Now ora2pg translate to_char to varchar and result is not expected. I understand so this behave is nice when user has not Orafce, but it should be disabled in configuration.

**Comment by darold** [comment]
Ok, I don't remember this. So I will add a directive USE_ORAFCE and when enabled we will be able to disable some translation.

**Comment by okbob** [comment]
I had same idea - but I am unsure if it is not too big granularity. Maybe can be documented good configuration for Orafce.

**Comment by darold** [comment]
I agree that this remove some flexibility in what can be translated and how, but there is already lot of configuration directives and looking at the transformations that could be problematic I think that we can just limit the USE_ORAFCE action to some translations, not all covered by Orafce.

Commit 566c8b8 adds this feature describe as follow in the config file and documentation:
```
    USE_ORAFCE
        If you want to use functions defined in the Orafce library and
        prevent Ora2Pg to translate call to these functions, enable this
        directive. The Orafce library can be found here:
        https://github.com/orafce/orafce

        By default Ora2pg rewrite add_month(), add_year(), date_trunc() and
        to_char() functions, but you may prefer to use the orafce version of
        these function that do not need any code transformation.
```

These are the functions I that can be covered by this directive. For example I don't want it to be used to enable Orafce decode() function instead of translation to CASE statements, but keep it for translation that can break the plpgsql code or may return incorrect result.

If you see other translation that might be covered by the USE_ORAFCE directive, please let me know.

**Comment by okbob** [comment]
ok
Thank you very much
