### ISSUE TITLE
Array types management in plpgSQL

### ISSUE THREAD

**Issue by edelanoe** [darold/ora2pg#534]
One of my packages, named PCK_INT, defines this:
   TYPE Itr_Product_List IS TABLE of GEASTRUCT.Itr_Product%ROWTYPE;  --GEASTRUCT.Itr_Product is a table
which is translated to a standalone TYPE declaration:
   CREATE TYPE pck_int.itr_product_list AS (itr_product_list GEASTRUCT.Itr_Product[]);

Unfortunately, such type is "not" useable in functions: If I try to access it with a subscript, I get the error:
   ERROR:  subscripted object is not an array

Postgres Doc suggests that the TYPE should be created another way:
"To indicate that a type is an array, specify the type of the array elements using the ELEMENT key word."

Is there a way to
- correct this type translation, so that it is really seen as an array at runtime ?
- replace all occurrences of such a type "Itr_Product_List" by "GEASTRUCT.Itr_Product[]" ?

Tell me if you need a sample code...
Best Rgds.

**Comment by darold** [comment]
Seems to me that this is the right type conversion, TABLE OF `GEASTRUCT.Itr_Product%ROWTYPE` can be considered as an array of composite type. I think that the problem is more in the use of this type, there is probably an other way to write this code but this probably need code rewriting that Ora2pg can not do at this time.
