### ISSUE TITLE
empty Oracle BLOB to PostgreSQL NULL

### ISSUE THREAD

**Issue by venkatabn** [darold/ora2pg#559]
Hi All,

Is there a way to migrate all the Empty BLOBs in Oracle to NULL in PostgreSQL ? When i migrate using ora2pg with default settings, i get empty strings in postgresql columns. Any help will be appreciated here. 

Thanks !

Regards,
Ven

**Comment by darold** [comment]
Hi,

Yes, look at EMPTY_LOB_NULL configuration directive.

Regards,

**Comment by venkatabn** [comment]
Yes, i did have a look.

EMPTY_LOB_NULL was left at default and i get empty strings instead on NULLs in postgresql, changing it to 1 makes no difference. Was there a BUG which was fixed recently ? or am i missing something ? 

Regards,
Ven

**Comment by venkatabn** [comment]
Here is a test i did -

Oracle test table with empty blobs -
SQL>  insert into testlob values (1, empty_blob());

1 row created.

SQL> commit;

Commit complete.

SQL>  insert into testlob values (2, empty_blob());

1 row created.

SQL> commit;

Commit complete.

SQL> insert into testlob values (3, empty_blob());

1 row created.

SQL> commit;

Commit complete.

SQL> select * from testlob;

         C C1
---------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------
         1
         2
         3

Migrated to postgresql

ora2pg has "EMPTY_LOB_NULL          0"

[vbn@oracleclient esasv_sys]$ ora2pg -c ora2pg-testlob-data.conf
[========================>] 1/1 tables (100.0%) end of scanning.
[========================>] 3/1 rows (300.0%) Table TESTLOB (0 sec., 3 recs/sec)
[========================>] 3/1 rows (300.0%) on total estimated data (1 sec., avg: 3 tuples/sec)

Queries in the postgresql -

I get 0 rows when i say c1 is null

sctest=> select * from testlob where c1 is null;
 c | c1
---+----
(0 rows)

I get all the rows when i say c1=''
sctest=> select * from testlob where c1='';
 c | c1
---+----
 1 | \x
 2 | \x
 3 | \x
(3 rows)

Regards,
Ven

**Comment by darold** [comment]
Hi Ven,

Actually Ora2Pg force empty BLOB to be exported as NULL whatever is the value of EMPTY_LOB_NULL. The only case where empty blob are exported as empty string is when there is a NOT NULL constraint defined on the Oracle column. In this case Ora2Pg will export the empty blob as an empty string. If you want to force Ora2Pg to export them as NULL you must enable EMPTY_LOB_NULL and of course the destination PostgreSQL column must not have the NOT NULL constraint.

It seems that you don't have this behavior, perhaps this is because you don't have a recent version, in this case please use v18.2 it must works as explained above.

**Comment by venkatabn** [comment]
Hi Darold,

Upgrading to 18.2 makes the difference !
Thank you for your help !

Regards,
Ven
