### ISSUE TITLE
insert or update on table "soandso" violates foriegn key constraint .. 

### ISSUE THREAD

**Issue by jjksaji** [darold/ora2pg#632]
Hi All, 
New to this forum, I am more into Linux basic system administration, recently I have taken interest in building up skills in database migration, because I fell there will be very good market for the Database migration projects from Oracle to PostgreSQL. 

Now I am doing my preparation by testing out migration from Oracle 11 to postgresql 8.4.20. I was successful in migrating the tables, now trying to migrate the data using TYPE INSERT 

I have kept the "EXPORT_SCHEMA 1" options  for "exporting Oracle schema to PostgreSQL schema"
EXPORT_SCHEMA   1
following is the error 

> ERROR:  insert or update on table "ad_alert" violates foreign key constraint "calertprocessor_adalert"
> DETAIL:  Key (ad_alertprocessor_id)=(100) is not present in table "ad_alertprocessor".

Advice requested to by solve this error and move forward

Thanks 
Joseph John

**Comment by darold** [comment]
Sorry for the response delay, I hope you find the solution by yourself.  The best solution is to import your constraint and foreign keys after data import, this will boost data import too. Otherwise you can enable DROP_FKEY configuration directive, it will drop all foreign keys before all data import and recreate them at the end of the import.

**Comment by jjksaji** [comment]
Thanks a lot,
I did using importing constraint and foreign keys after data import, but
not sure I have done it properly
will update to the list, my findings

Thanks
Joseph John
00971-50-7451809
