### ISSUE TITLE
How to do direct from oracle to Postgres, no intermediate file

### ISSUE THREAD

**Issue by fatfrabbit** [darold/ora2pg#66]
Actually, my database's table are very big,
how to do a direct from oracle using ora2pg to Posgres without using intermediate 
temporary file?

Thanks,

Dominica

**Comment by exislow** [comment]
Is it possible to overwrite the WHERE configuration from the conf file with a command line parameter? E.g.

`ora2pg -c my.conf -W 'ROWNUM > 2'

**Comment by darold** [comment]
No

**Comment by gvijay07** [comment]
Hi Darold,

The discussion here, helped me in migrating the data for some of the tables from oracle to postgresql. Below is the syntax format I have followed:

ora2pg -N <schemaname> -a <tablename1> -c ora2pg.conf -t COPY -j 8 > output
ora2pg -N <schemaname> -a <tablename2> -c ora2pg.conf -t COPY -j 8 > output
ora2pg -N <schemaname> -a <tablename3> -c ora2pg.conf -t COPY -j 8 > output
ora2pg -N <schemaname> -a <tablename4> -c ora2pg.conf -t COPY -j 8 > output
ora2pg -N <schemaname> -a <tablename5> -c ora2pg.conf -t COPY -j 8 > output

While doing so, I have few doubts raised.. can you pls help suggest how to handle in below cases:

1) Since my source and target schema names are same, no issues to follow the above syntax. what if source & target schemas differ and what will be the syntax in this case to load directly?
2) Is there a way to load data into multiple tables parallelly like execute data load on multiple tables simultaneously and if so what will the syntax for this?  

Thanks for your support on this.

**Comment by darold** [comment]
Hi,

First I doubt that `-j 8` gives helps more than `-j 4`, usually `-j 4` is a maximum value to parallelize the output to file or PostgreSQL unless you have seem good speed improvement between -j 4 and -j 8. What can help to improve data migration speed is to parallelize table export, using `-P` option, `-P 4` for example. Of course it depends of the number of cores available.

Using `ora2pg --help` will give you all the options that can be used and look at documentation for more information.
