### ISSUE TITLE
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid input syntax for integer: "41.9999999999999"

### ISSUE THREAD

**Issue by w0pr** [darold/ora2pg#660]
This is with Ora2Pg v18.2.

Oracle NUMBER(22) column with value 42 gives error on command

 _ora2pg -t COPY -o data.sql -b ./data -c ./config/ora2pg.conf_

```
DBD::Pg::db pg_putcopyend failed: ERROR:  invalid input syntax for integer: "41.9999999999999"
CONTEXT:  COPY conf_sys_control_optic, line 4, column margin_left: "41.9999999999999" at /usr/local/share/perl/5.26.1/Ora2Pg.pm line 12761.
FATAL: ERROR:  invalid input syntax for integer: "41.9999999999999"
CONTEXT:  COPY conf_sys_control_optic, line 4, column margin_left: "41.9999999999999"
```

Somehow the BigInt is interpreted as a float...

Oracle:
![image](https://user-images.githubusercontent.com/8257055/41867304-0cab1b08-78b3-11e8-8f6a-04563a4316c1.png)

PostgreSQL:
![image](https://user-images.githubusercontent.com/8257055/41867358-3b60a242-78b3-11e8-8dd7-bdb3a9a60c6b.png)

**Comment by darold** [comment]
Ora2Pg export NUMBER(22) as bigint, but you might find some columns that store decimal values during data import. In this case you need to change the destination data type. If you have too much columns with this problem then you can choose to export NUMBER(22) as numeric instead by setting DEFAULT_NUMERIC to numeric.

**Comment by darold** [comment]
No the value 41.9999999999999 is the value really returned by Oracle, you are seeing 42 because your Oracle tool or Oracle itself is returning an integer for you, Oracle is lying to you :-)
```
SQL> create table t1 (test NUMBER(22));

Table creee.

SQL> insert into t1 values (41.9999999999999);

1 ligne creee.

SQL> select * from t1;

      TEST
----------
	42

SQL> 
```
Actually, NUMBER(22) is a numeric and it accept decimal number. Ora2Pg is just retrieving the real stored value.  Also note that most of the time NUMBER(22) can be safely exported as bigint, this is a common use and this is why it is the default in Ora2Pg.

**Comment by w0pr** [comment]
Yeah, got it; good thing we're going for PostgreSQL. ;)
