### ISSUE TITLE
Issuing rollback() due to DESTROY without explicit disconnect() with ora2pg v19.0

### ISSUE THREAD

**Issue by adebie** [darold/ora2pg#683]
Hello,

I'm trying to evaluate the cost of an Oracle to PG migration for some of our databases.

It's going fine except for one db for which I receive the following error:
Unmatched ) in regex; marked by <-- HERE in m/\bSUFFIX'||r_get_suffixes.SUFFIX_ID) <-- HERE ;\s+/ at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 16442.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PORT=1522)(PROTOCOL=tcp)(HOST=theHost))(CONNECT_DATA=(SID=theDB))) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 16442.

The command I use is the following:
ora2pg -p -d -t SHOW_REPORT -s dbi:Oracle:host=theHost;sid=theDB;port=1522 -u theUser -w thePassword --estimate_cost --cost_unit_value 5

The db is an Oracle 11.2.0.4.0 one.

And as mentioned in the title, I use ora2pg v 19.0.

Any clue of what's going wrong ?

Thanks,

Alain.

**Comment by MikeCaliffCBORD** [comment]
No help, but I am also looking into a conversion and getting the same error about "Unmatched ) in regex". The text from the error also looked similar, so I thought I would start by joining in here.

Server is running Oracle 12.1.0.2,
I _think_ I have the configuration file set to export a single table. Based on the error, the problematic line appears to be where the procedure AutoconfigureTPSRoles calls a logging function in a package from inside a loop. The line is:
dcs_output.put_line_d('AutoconfigureTPSRoles',4,'Adding role '||to_char(therole_id)||' for server_sid'||to_char(row_server_sid));

I can provide additional context if that would help.

Sample run:

C:\Strawberry\perl\site\bin>ora2pg.bat -d
[2018-08-30 18:12:48] Ora2Pg version: 19.0
[2018-08-30 18:12:48] Trying to connect to database: dbi:Oracle:host=foobar;sid=ORCL;port=1521
[2018-08-30 18:12:53] Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
[2018-08-30 18:12:53] Looking forward functions declaration in schema XXXXXXX.
[2018-08-30 18:12:53] Looking at package access_trigger_p...
[2018-08-30 18:12:54] Looking at package AlarmActionSqlPackage...
[2018-08-30 18:12:54] Looking at package alarmdata...
[2018-08-30 18:12:54] Looking at package AlarmNotify_P...
[2018-08-30 18:12:54] Looking at package Ap_Gen...
Unmatched ) in regex; marked by <-- HERE in m/\bserver_sid'||to_char(row_server_sid)) <-- HERE ;\s+/ at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 16442.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=foobar)(PORT=1521))(CONNECT_DATA=(SID=ORCL))) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 16442.

**Comment by darold** [comment]
Please send me the Oracle DDL of package `Ap_Gen` to my private address - gilles AT darold DOT net

The problem comes when Ora2Pg is parsing this package to try to extract the function/procedure declaration.

**Comment by darold** [comment]
Thanks to @adebie commit 548612d should fix this issue. Please upgrade to latest development code.

**Comment by adebie** [comment]
The new code solved my problem.
Thanks for the swift answer.

**Comment by darold** [comment]
Good news, @MikeCaliffCBORD can you confirm that your issue is solved too and close the issue if this is the case?
