### ISSUE TITLE
ora2pg write process uses 100% of cpu. 

### ISSUE THREAD

**Issue by adebie** [darold/ora2pg#706]
Hello,
We are exporting an Oracle schema and looking at the server where ora2pg runs, we see that the ora2pg-writing process uses 100% of cpu (the server running ora2pg is not the server where the Oracle db runs)
Is this normal ?
![cpu100-ora2pg](https://user-images.githubusercontent.com/42832630/46343836-65535700-c63f-11e8-8a6e-9526924a9bcf.png)
The server has 24 processors and 190Gb of memory.
The command used to perform the export is the following:
```
ora2pg -j 6 -J 3 -t COPY -o data.sql -b $namespace/data -c $namespace/config/ora2pg.conf
```
Here are some ora2pag parameters from the config file:
```
DATA_LIMIT 90000
BLOB_LIMIT 100
TRANSACTION    serializable
```

**Comment by darold** [comment]
Hi,

Yes this is normal, ora2pg must transform all data and write them to disk. Here you are using 6 core per Oracle extractor (3) to write the data, which mean 18 core at a maximum. The -J option is interesting when you have a huge Oracle table, especially with BLOB, otherwise I would recommend to use -P instead.

Note that you can load data directly into PostgreSQL to avoid writing data to disk twice.

**Comment by adebie** [comment]
Thanks for the clarification, Gilles.
Writing directly to PostgreSQL is, unfortunately, not an option for us at present time.

What about the combination of -J and -P ? if we have huge tables, small tables and BLOB.

**Comment by darold** [comment]
The combination of -J and -P option is in my TODO list since 2015 when it was reported by Tom Boden on SourceForge, Unfortunately I still don't have the spare time to develop it and until now this is not the priority.

**Comment by adebie** [comment]
OK, thanks for your feedback.
