### ISSUE TITLE
ora2pg fully not migrated the oracle package to pg

### ISSUE THREAD

**Issue by buragaddapavan** [darold/ora2pg#739]
ora2pg didn't migrate function LOAD_STATUS_CACS_FILE and procedure VALIDATE_CACS_FILE from package OB_CFS_IMPORT_PKG.

attached package ddl OB_CFS_IMPORT_PKG.
[package1.txt](https://github.com/darold/ora2pg/files/2693761/package1.txt).

ora2pg 19.1 didnt generate DDL's for function LOAD_STATUS_CACS_FILE and procedure VALIDATE_CACS_FILE.

**Comment by darold** [comment]
The reason is that you have functions and procedures declared into function LOAD_STATUS_CACS_FILE and procedure VALIDATE_CACS_FILE. Ora2Pg doesn't support nested declaration of function/procedure, you have to extract these nested declaration outside the parent function. You will also need to add them to the package declaration. See nested procedure update_ob_import_status for example.
