### ISSUE TITLE
Slow data extract of table containing blob

### ISSUE THREAD

**Issue by M-Hauff** [darold/ora2pg#776]
I like ora2pg. I use it all the time, but this is the first time migrating BLOBs and I'm having a problem.

I'm on ora2pg 18.2. I have extracted other oracle DBs and migrated to PostgreSQL without issue.
This time I cannot extract one table with a BLOB column. 
For starters the copy is extremely slow, so I'll nohup the copy and the mount point will fill to capacity.  The mount point is 103G and the table is 54G so there is plenty of room. I have no clue as to why the file produced by the copy command is larger than the table itself. 

For example. watching the output from 
ora2pg -t COPY -L 500 -o data.sql -b ./data -c ./config/ora2pg.conf -J 2

With 606 rows extract I'm at a 900+ megs; it's a riddle to me. I f I were to let it continue it would fill the mount point. I have attached my conf file. Any help is greatly appreciated.

**Comment by M-Hauff** [comment]
[ora2pg_conf.txt](https://github.com/darold/ora2pg/files/3031729/ora2pg_conf.txt)

**Comment by M-Hauff** [comment]
Closed by acident.

**Comment by darold** [comment]
Hi,

The file produced by the copy command is larger than the table itself because this is a text representation of your BLOB and all bytes are encoded. If you don't have enough disk space or want to improve performances you must use direct import into PostgreSQL using the PG_DSN configuration directive. Storage in PostgreSQL takes less size.

Also about performances as each byte must be encoded using more CPU and memory helps a lot. For example you can parallelize data export from the Oracle table using `-J 4` and parallelize encoding and data import using `-j 2`. This mean that you need at least 8 cores on the Ora2Pg host.

If your issue is disk space and you don't care about performances you can use data compression with giving a .gz extension to the output file (OUTPUT directive or -o option) but in this case you will not be able to use multi-process.

Regards

**Comment by M-Hauff** [comment]
Thank you,

That makes sense. I will to a direct import into postgres.

Matt H.

Sincerely,
Matt Hauffman
Oracle DBA / Postgres DBA
Digital Aviation - Operations -  Global Navigation Services - Technology
-----------------------------------------------------------
Jeppesen
A Boeing Company
Mobile : 720-206-7997  || matthew.hauffman@jeppesen.com
55 Inverness Drive East |Englewood, CO 80112
www.jeppesen.com<http://www.jeppesen.com/>
Friday Virtual Worker

**Comment by M-Hauff** [comment]
Thank you for your help.
