### ISSUE TITLE
defunct processes of ora2pg

### ISSUE THREAD

**Issue by g1soori** [darold/ora2pg#850]
Hi Darold,
We noticed below defunct OS processes while running the ora2pg migration. We transferred 12 tables with the below mentioned command. 11 out of 12 were successfully migrated but last one kind of stop updating the log file for around 1.5 hours. Then we noticed these defunct processes were running on the OS. This table is around 1TB size. After performing the row count comparison between oracle and PG we noticed that last table row count not matching between two databases. Appreciate if you can explain about these defunct processes.

```
Oracle version - 10.2
PG version - 11.1
ora2pg version - 20
ora2pg command - 
nohup ora2pg -t COPY -J 24 -j 24 -P 10 -L 100000 -c ora2pg-ulsd.conf -a "<Table Names>"  > migrate-$(date +%Y-%m-%d-%H%M%S).log 2>&1 &
ora2pg server spec - 24 cores / 48G RAM (separate server for ora2pg)

postgres  3765  3088  0 11:19 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3785  3088  0 11:19 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3811  3088  0 11:20 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3832  3088  0 11:20 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3861  3088  0 11:20 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3894  3088  0 11:21 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3914  3088  0 11:21 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3935  3088  0 11:22 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3956  3088  0 11:22 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3977  3088  0 11:22 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  3998  3088  0 11:23 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4017  3088  0 11:23 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4036  3088  0 11:24 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4058  3088  1 11:24 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4080  3088  1 11:24 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4102  3088  1 11:25 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4122  3088  1 11:25 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4142  3088  1 11:26 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4164  3088  2 11:26 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4183  3088  2 11:26 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4202  3088  3 11:27 pts/2    00:00:02 [ora2pg - sendin] <defunct>
postgres  4219  3088  3 11:27 pts/2    00:00:01 ora2pg - sending data from table 
postgres  4236  3088  7 11:27 pts/2    00:00:01 ora2pg - sending data from table
```

**Comment by darold** [comment]
Options `-J 24 -j 24` means that Ora2Pg will use 576 cores (24 * 24), this is a bit too much for a 24 cores machine. You might use `-J 6 -j 4` or perhaps `-J 8 -j 3` will be better. 

The defunc process will be killed when the last running process ends, this is not important, what is important is to not exceed system resources, one ora2pg process will use 100% of one core.

In your case if you have a table of 1.5TB you shall exclude it from the export and export this table alone with `-J12 -j 2` for example or why not `-J 24` only if you see that the export is faster. To exclude this table add `-e MYBIGTABLE` and to only export this table add `-a MYBIGTABLE`

**Comment by Jeewansoori** [comment]
Hi Darold,
Thank you very much for the quick response. Here are some more details about our oracle database. It takes around 20 hours to perform the migration. Appreciate if you can provide some more recommendations for optimal ora2pg settings.

Total DB Size = 4TB
Total number of rows = 1.5 billion

We did a quick testing with -J6 -j4 settings but it can only transfer 80,000 records/s compared to 200,000 records/s in our original settings. Just trying to figure out optimal settings without losing any data.

Thanks and appreciate your support.

**Comment by darold** [comment]
Ah ok, sorry I did not see that you've set `-P10`. When `-P` is used this disable the `-J` option so with your command:
```
ora2pg -t COPY -J 24 -j 24 -P 10 -L 100000 -c ora2pg-ulsd.conf -a "<Table Names>"
```
you are trying to use 240 cores, using `-P 8 -j 4` might be better.

The problem with current Ora2Pg multi-process implementation and your command is that if you have a huge table it will only use a single process to extract data from the Oracle table. This is good if you have 10 table of the same size but not with some tables that have most of the data. This is why it is best to exclude those table from the first run and to use `-J 10` instead of `-P 10` for the huge tables to parallelize data extraction from a single table. If the first command takes lot of time too you can optimize the time spent by running 2 ora2pg commands, one to export "small" table with `-P 2 -j 2` and the huge table using `-J 10 -j 2` for example. It depends if you want to chain or parallelize the export.

In my experience most of the tables can be exported quickly, let's say in 20 minutes maximum, and some huge tables usually with BLOBs will take hours. Separating the export in two or more chained steps is better.

**Comment by darold** [comment]
You should also reduce DATA_LIMIT to 25000 or 50000 maximum: ` -L 25000`

If you have a maximum of 200,000 tuples/second `-P 10` will potentially load 2,000,000 rows in memory for nothing. Using `-P 8 -j 3 -L 25000` could give you a better throughput or at least the same if this is the maximum that can be reach. Can you confirm?

**Comment by Jeewansoori** [comment]
Thanks Darold. I tried with last options you mentioned above but recs/s doesn't go beyond 40,000. 
Anyway we ran another round of testing and failed the migration on the same point. It seems to be nothing to do with server performance or transfer speed. It failed during the same partition on both cases.
Is there a way to transfer single partition without migrating entire table ? 
Does ora2pg transfer data sequentially ? Is there a way to find out the failed records and try to insert them manually ? To find out whether there are some discrepancies in data.

**Comment by darold** [comment]
LOG_ON_ERROR
```
# Enable this directive if you want to continue direct data import on error.
# When Ora2Pg receives an error in the COPY or INSERT statement from PostgreSQL
# it will log the statement to a file called TABLENAME_error.log in the output
# directory and continue to next bulk of data. Like this you can try to fix the
# statement and manually reload the error log file.
```
It will log the entire COPY block that fail, the number of tuples in that block depend of DATA_LIMIT.

Can you post the error message reported by Ora2Pg
About partition export have you tried to use  `-a PARTITION_NAME`?

Also you need to use latest development code if this is not already the case.

**Comment by ryansoon** [comment]
hi Darold, 
Teammate here with @Jeewansoori. 

quick question if you can help: does ora2pg have any row transaction limit of 2 billion or 4 billion per the oracle table (partition) to be migrated. It just seems strange that our current migration is failing at the 4 billion mark during both previous run.

and we are also referring to this write up from 2ndquadrant: https://www.2ndquadrant.com/en/blog/managing-freezing/

**Comment by darold** [comment]
You should look at PostgreSQL log, on Ora2Pg or Perl side there is no limitation unless perhaps if you have a very old version of Perl but I guess that this is not the case. 

What is the ora2pg error message? If a migration "thread" crash the main process will detect that a child fail and you might have an error message. The ora2pg command might also exit with a value > 0.

I have a couple of questions:

Does a `SELECT count(*) FROM partitioned_table;` reports a different count from Oracle and PG or are you using the count from statistics?
How much rows are missing and what is your value for DATA_LIMIT or `-L` option?
Are you using Ora2Pg latest development code `wget https://github.com/darold/ora2pg/archive/master.zip`?

**Comment by ryansoon** [comment]
using:
# perl -version
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

there is no error being logged which is probably correct because the child is defunct (not really crash)

the select count(*) between the oracle and pg reports the same row but we have to jump thru hoop to make it work. we basically drop the front 8 partition then ora2pg. next restore, then drop the back 8 partition then ora2pg. we are trying to avoid the defunct issue explained earlier.

we are using the latest
# ora2pg -v
# Ora2Pg v20.0

**Comment by darold** [comment]
And in PostgreSQL log any error that could explain this 4 billion limit?

**Comment by Jeewansoori** [comment]
On ora2pg side -
----------------------
We used the same settings as our initial testing.
ora2pg -d -t COPY -J 16 -j 16 -P 1 -L 100000 -c ora2pg-uapp.conf -a "APP_RESULT" 

Enabled LOG_ON_ERROR feature and debug mode. There is no error file created or error in output log. ora2pg hung around after migrating 75% of the table. We dropped the few successfully migrated partitions from oracle end and initiated the transfer again. But failed after migrating same amount of rows from the table. There are defunct processes in ora2pg server as below.

postgres 10784     1 95 Feb27 ?        18:08:08 ora2pg - querying table APP_RESULT
postgres 17590 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17592 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17593 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17595 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17596 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17598 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17600 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17601 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17603 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17604 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17606 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17607 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17609 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17611 10784  0 Feb27 ?        00:00:07 [ora2pg - sendin] <defunct>
postgres 17612 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>
postgres 17614 10784  0 Feb27 ?        00:00:06 [ora2pg - sendin] <defunct>



On PostgreSQL side
------------------------
No errors or warnings on PG logs related to 4 billion limit or anything related to failure.  When ora2pg is on hung state, we can see below session in PG end.

[local]: postgres@postgres=# select * from pg_stat_activity where client_addr='125.244.248.34';
 datid | datname |  pid  | usesysid | usename | application_name |   client_addr   | client_hostname | client_port |         backend_start         | xa
ct_start |          query_start          |         state_change         | wait_event_type | wait_event | state | backend_xid | backend_xmin |  query  |
  backend_type
-------+---------+-------+----------+---------+------------------+-----------------+-----------------+-------------+-------------------------------+---
---------+-------------------------------+------------------------------+-----------------+------------+-------+-------------+--------------+---------+
----------------
 16394 | ulapp    | 27710 |    16384 | uapp    |                  | 165.204.218.144 |                 |       42260 | 2020-02-27 15:08:34.284985+08 |
         | 2020-02-27 15:08:34.345878+08 | 2020-02-27 15:08:34.34593+08 | Client          | ClientRead | idle  |             |              | COMMIT; |
 client backend
(1 row)

[local]: postgres@postgres=#

**Comment by ryansoon** [comment]
To add on to @Jeewansoori note above, the issue might be with the variable or variables used in ora2pg. Probably an unsigned integer or similar: 2 to the power of 32 = 4294967296. our current hypothesis is, during the migration, ora2pg hits this limit and resulted in the defunct child processes and the parent hung at the 4 billion rows. And hence there is no error, warning or dumps anywhere since it hung. 

Also, we verified the txn ID on the PG side. nothing exceeding 200K. so our earlier thoughts that the issue might lie with the PG txn ID, might not be true.

**Comment by ryansoon** [comment]
to addon, on all occasion that the defunct processes were observed and parent hung, the total number of rows migrated were 4294900000.
4,294,900,000 is suspiciously close to the 4 bytes unsigned max value 4,294,967,296 and adding another 100000 will cause an overflow.
Could there be some maximum for the total number of records to copy/migrated?

**Comment by Jeewansoori** [comment]
Hi Darold, 
We were able to find out the root cause of our issue. We have set the DISABLE_PARTITIONS=1 in our ora2pg.conf file which caused the ora2pg to migrate partitioned table as a single large table. Once we set the DISABLE_PARTITION=0, ora2pg started migrating data on oracle subpartition level and it didn't hit the 4 billion rows limit. In summary, ora2pg seems to be having limitation of migrating 4 billion rows in single table/thread but we can overcome it by letting it transfer subpartitions/partitions of those large tables.
Thanks again for your speedy response on this matter.

Regards
Jeewan

**Comment by darold** [comment]
Good news, thanks for the feedback. Can you tell us how much time it takes to migrate the 4Tb of data, In the first post you said 20h but I guess that with partitioning enable it was faster?

**Comment by Jeewansoori** [comment]
our 4TB database consists of 12 tables. 5 out 12 tables are partitioned tables. I didn't capture exact time details but here are estimates. It took around 15 hours to complete the data migration. Then it took another 15+hours for index creation. We created indexes after migrating the data.
We have many more similar databases to migrate and will share the exact figures later.
