### ISSUE TITLE
Command is long running without any exception

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#869]
While  executing below command it goes ever ending process without any error or output.

ora2pg -c C:\ora2pg\testlogAuth_DBSNMP\config\ora2pg.conf -t SHOW_REPORT --estimate_cost --cost_unit_value 10 --dump_as_html >testlogAuth_DBSNMP_AzurePostgreSQL.html

how we can check the logs or how to find what is the blocker.

Any lead to solve this issue will be great.

**Comment by AwdotiaRomanowna** [comment]
add debug (-d) so you can see at which point it stucks. check first if you have connectivity to your db: `ora2pg -c config/ora2pg.conf -t SHOW_VERSION`

check if ora2pg already connected to oracle - if yes you might need to update stats.

btw. it happened to me once when instead of -- i pasted some other characters, because did copy&paste and somehow strange characters were passed. so rewriting it manually helped
