### ISSUE TITLE
Almost with every invalid objects in  Migration assessment report there are keys 1- Test, 2- Size, 3- Concat. So can any one explain these keywords in brief and how to deal with these during migration.

### ISSUE THREAD

**Issue by deepakp555** [darold/ora2pg#870]

**Comment by AwdotiaRomanowna** [comment]
test and size are always there. If you have something like that:

```
Function my_function total estimated cost: 3
TEST => 2
SIZE => 1
```

It means that you would need 10 minutes for testing - so call SELECT my_function() and check if everything is ok.
size - 5 minutes in this case- because it is small function

so it summed up to 3 - 15 minutes becasue by default 1 means 5 minutes

If you use CONCAT (||), pragma, DBMS_ etc. it means this construct/feature/package it was found in the body of the function and you will see estimated cost of it

**Comment by darold** [comment]
Commit 9747129 add explanation of these two assessment value in the documentation. As @AwdotiaRomanowna explained:

```
In the migration assessment details about functions Ora2Pg always include per
default 2 migration units for TEST and 1 unit for SIZE per 1000 characters in
the code. This mean that by default it will add 15 minutes in the migration
assessment per function. Obviously if you have unitary tests or very simple
functions this will not represent the real migration time.
```
