### ISSUE TITLE
Is it possible to 'delta refresh / incremental load' using ora2pg?

### ISSUE THREAD

**Issue by joedbadmin** [darold/ora2pg#874]
I want to load the data incrementally. Is it possible with ora2pg?
if so, whats the parameters / requirement / an example syntax for that?
Can you please let me know? Thanks much in advance.

**Comment by joedbadmin** [comment]
@darold - Any help on this? Much appreciated!

**Comment by darold** [comment]
Ora2Pg have two possible way for incremental data import. See WHERE clause but need columns allowing to find the new rows, it do not support delete and update. For a more advanced incremental import see the experimental DATADIFF. Both are explained the the ora2pg.conf file. Otherwise I guess that an ETL like Kettle will do the job.

**Comment by joedbadmin** [comment]
Thank you!
