### ISSUE TITLE
> @darold Thanks for instant reply

### ISSUE THREAD

**Issue by Swapnil24051992** [darold/ora2pg#905]
> @darold Thanks for instant reply
> I am facing following issue while running scanner:
> Can't connect to data source ''dbi:Oracle:host=localhost;SID=ORCL;port=1521'' because I can't work out what driver to use (it doesn't seem to contain a 'dbi:driver:' prefix and the DBI_DRIVER env var is not set) at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 1624.
> Running: ora2pg -c ora2pg.conf -t SHOW_REPORT --dump_as_html --estimate_cost -s 'dbi:Oracle:host=localhost;SID=ORCL;port=1521' -n 'CDI' >> "output/schema_CDI-report.html"
> 
> Could you help me out with this

_Originally posted by @Swapnil24051992 in https://github.com/darold/ora2pg/issues/896#issuecomment-649380707_

**Comment by darold** [comment]
If you are looking for "instant" reply you should contract a commercial support you should contact one of the excellent companies near of you listed in the [http://www.postgresql.org/support/professional_support](PostgreSQL Professional Services) page, they all do great job.

About your issue I don't know what happen, the DSN look good, at least if I use it it works. If the ora2pg command shown by ora2pg_scanner (`ora2pg -c ora2pg.conf -t SHOW_REPORT --dump_as_html --estimate_cost -s 'dbi:Oracle:host=localhost;SID=ORCL;port=1521' -n 'CDI'`) works when executed individually I guess there is an issue with ora2pg_scanner on Windows plateform. Otherwise I guess that your installation is not conform, perhaps the DBD::Oracle Perl module is not well installed.
