### ISSUE TITLE
[Question] DATADIFF functionality, how to generate export file?

### ISSUE THREAD

**Issue by pilgrim-push** [darold/ora2pg#914]
Hello @darold,

Thx for the great tool, it much helps in our migration to PG. But I have a question about DATADIFF function - I tried to use it but still didn't get how to form an export file with data for DIFF. All data in the export file is forming with suffix "_ins". Am I right that it is a manual procedure to form the export file where need to put data in "_ins", "_del", "_upd" manually?

Sorry, I'm a newbie in Oracle and didn't get how to use this feature for incremental migration; Is it possible somehow to generate an export file with data changed from the last migration only?

**Comment by SebAlbert** [comment]
What it does is this:
* Instead of deleting from the existing Postgres table and inserting to the existing Postgres table, it SELECTs the "rows to be deleted" into an intermediate table with suffix "_del" and the values to be inserted are inserted into a table with suffix "_ins".
* Then it compares - inside Postgres - those two tables and DELETEs identical rows from both (so they are not deleted from the real table only to be inserted again)
* Afterwards, it DELETEs the remaining rows in the _del table from the real table, and inserts the remaining rows from the _ins table into the real table.
* Optionally, if you have a PRIMARY KEY on the real table, it can also detect rows that are not identical in _del and _ins, but do have the same value for the primary key, and rewrite them to an UPDATE rather than a DELETE followed by an INSERT. Those updates are stored in an intermediate table with suffix "_upd" and discarded from the "_del" and "_ins" tables before their respective execution as well.

While you can do things manually with the _ins, _upd and _del tables before they are dropped again (via the `DATADIFF_BEFORE` and `DATADIFF_AFTER`, where a function can be specified that will be called with those tables as arguments (regclass, the Postgres type for "reference to a table")), the normal functionality should be performed automatically.

Please note the following:
* The entire thing does not work with partitioned tables or parallel execution.
* All the data is still being extracted from Oracle every time, only in Postgres the identical rows will be annihilated so that the target table(s) do not experience unnecessary DELETEs and INSERTs.
* For the purpose of "updating" data regularly, you would usually want to specify the `DELETE` configuration in addition to a `WHERE` configuration. If you do not have a `WHERE` condition, then still activate `DELETE` with a condition of `1=1` or similar.

**Comment by pilgrim-push** [comment]
Ok, thank you for the great explanation. It becomes much clear.
To make a real incremental migration need to use WHERE clause in additional to DELETE configuration

I close the issue as resolved. Thank you so much
