### ISSUE TITLE
Migration test queries

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#944]
Darold, would you mind share me the queries which you are using to test the migration. Sometime I am seeing the differences between your count and my count. Please help me with the queries.

**Comment by darold** [comment]
All queries are built dynamically in Ora2Pg source code, i you want to look at them read file lib/Ora2Pg.pm and search for the following functions:
```
sub _count_object
sub _count_check_constraint
sub _test_table
sub _test_function
```
the follow the code to get the right queries.

Oracle queries used in test count are the same that are used to export the objects so if Ora2Pg doesn't report a difference between object count everything have been imported into PostgreSQL. If you are surprised because you think you have more object in the Oracle database, get a list of these objects and what they really are and check if they must really be exported. Usually Ora2Pg has the right number :-)

**Comment by naveenjul29** [comment]
Sure Darold, I will go through the above and confirm. As usual you are the best :)
