### ISSUE TITLE
Tables are not exported

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#950]
Hi Darold

Hope you are doing great !!

Couple of issues:

1. some of the tables exported as CREATE TABLE and some of the tables exported as CREATE UNLOGGED TABLE, not sure why?

2. couple of the tables are not exported due to the below reason, is there any chance to export these tables also using ora2pg?
**COMMENT ON TABLE tablename  IS 'snapshot log for master table tablename;**

3. Sometimes, I exported the tables using Oracle SQL Developer and passed the SQL file as input to ora2pg as parameter. When I export the tables/views, they exported along with the storage parameters PCTFREE, PCTUSED etc., They are not deploying into PostgreSQL due to these parameters. Is there a way to deploy these objects?

**Comment by orenbouni** [comment]
1) Oracle Tables can be created with the Nologging option, in PostgreSQL it is  UNLOGGED.    the Option of UNLOGGED is for faster insert

**Comment by naveenjul29** [comment]
can I please have an update on point 2 and 3?

**Comment by darold** [comment]
point 2: this is not because of the comment, this is because these tables ares snapshot for materialized view so they don't have to be exported.

point 3: post an example of DDL code exported by Oracle SQL Developer that is failing to be well translated by Ora2Pg. I am not a magician, I can not fix if I can not reproduce.

@naveenjul29 you are now a little aware on how Ora2Pg support works, you should have found the answer for the both points by yourself.
