### ISSUE TITLE
How to handle pl/sql specifics

### ISSUE THREAD

**Issue by unrandom123** [darold/ora2pg#964]
Hello.
I exported packages (-T package) from oracle, and I wonder what happens with things that cant be translated?
For example calls to dbms_* packages (or other things)
Are they listed somewhere, or I will find them when things don't work when I try to run them in postgres?

I see some warnings about ref cursor not beeing supported, or rearangement of parameters so default values are last.
But aren't there more things?
It would be nice with more warnings, if possible.

And to have all warnings collected in one file. I get some in a log file when doing redirect of stdout and stderr to a file, but some are still echoed to the screen. Is that possible to have that?

**Comment by darold** [comment]
Incompatible code is preserved, actually Ora2Pg doesn't touch code that it can not translate. You will have an error when you will try to import the code. Ora2Pg throw warning with some code translation so that you can be more careful when importing the code. The stderr and stdout output can be redirected to a file at command line.
