### ISSUE TITLE
 ERROR:  invalid byte sequence for encoding "UTF8": 0xae

### ISSUE THREAD

**Issue by kirandba-hub** [darold/ora2pg#974]
Hi Darold,

When i am importing the table data into postgresql,it is failing with below error message.

gdsrm_sdm=> \i /u02/GDSRM_SDM_DATA_MIGRATION/CONFIG_PRODUCT_data.sql
psql:/u02/GDSRM_SDM_DATA_MIGRATION/CONFIG_PRODUCT_data.sql:783: ERROR:  invalid byte sequence for encoding "UTF8": 0xae
CONTEXT:  COPY config_product, line 159

Can you please help me out to sort out this issue.

Best Regards,
Kiran

**Comment by kirandba-hub** [comment]
Issue solved

**Comment by marie-joechahine** [comment]
@kirandba-hub How did you end up fixing this issue? I am facing the same problem at the moment.

Thanks in advance.

**Comment by marie-joechahine** [comment]
It turns out the files being generated were in ANSI encoding, which I am not sure I understand since I thought the default was UTF8. When I saved the files again with encoding UTF8 and imported them to PostgreSQL it worked. 
@darold Do you have an idea why this might be happening, am I missing something in the configuration?
