### ISSUE TITLE
Tables export issue with Ora2pg

### ISSUE THREAD

**Issue by naveenjul29** [darold/ora2pg#999]
Not all the tables are not exporting with ora2pg tool. Below are the scenarios:
1.	Table Names having Special character “$” are not converted by Ora2pg.
         Examples: “AQ$_WF_BPEL_QTAB_G”, ”DR$EDR_PSIG_TEXTINDEX$I”
2.	Temporary Tables are Not converted  by Ora2pg
         Examples: "AZ_APIFWK_TEMP”
3.	Tables starting with SYS_ not exported.
        Example is SYS_IOT_OVER_145627
Is there any option to export all the tables in Ora2pg irrespective of any scenarios?

**Comment by darold** [comment]
The question is more why these objects should be exported? I have already replied to you about non exported table I have no new answer.

About global temporary tables this is different they are not exported because there is no equivalent in PostgreSQL but they will be supported in next Ora2Pg release though the use of the pgtt extension.
